### ISSUE TITLE
Cyberpunk 2077 : The start Pop-up hangs and crashes the game

### ISSUE THREAD

**Issue by theALFA-github** [Nukem9/dlssg-to-fsr3#101]
I have followed the instructions very carefully and installed both "DLSSTweaks by Emoose" and "dlssg-to-fsr3 by Nukem9" but when I try to run the game the start popup opens but hangs up. Can't click the "OK" in the pop-up or do anything for that matter. It shows the loading cursor when hovered above it but is not intractable. After a minute or so it crashes the game showing "Watchdog Timeout" error in the crash logs. Can anyone pls help...I really want to play the game with FSR 3.0 so I can try Ray-Tracing🥺

### My PC Specs ###
Asus TUF A15 Gaming Laptop
GPU - NVIDIA RTX 3050 Mobile 4GB
CPU - AMD Ryzen 5 4600H
RAM - 16.0 GB 
System - Windows 11

⁕Note : I have a bunch of mods installed. The System and all the drivers are up to date. GPU scheduling is turned on.

**Comment by Ghostman863** [comment]
try to remove everything and run without fsr3 mod. If it will work, then just copy dlssg-to-fsr3 files to folder with CP and run registry file included.

**Comment by DaleCulpin** [comment]
Have you tried without DLSSTweaks?

I've never used DLSSTweaks but this mod works okay for me in Cyberpunk 2077 (although it has crashed a couple of times when launching).

All I did was:

1. Merge the registry tweak
2. Copy the 2 .dll files to Cyberpunk x64 directory
3. Launch

**Comment by xjosob** [comment]
I am also having this issue when booting the game through the launcher. Running the game's exe instead works much better for me, though the popup still freezes sometimes.

**Comment by LiRunZhe** [comment]
I've been facing the same issue too. I've tried every possible solution, but whenever I launch the game and the message box pops up, the game crashes after a while.😭

**Comment by xjosob** [comment]
> I've been facing the same issue too. I've tried every possible solution, but whenever I launch the game and the message box pops up, the game crashes after a while.😭

Try to start the game through the exe directly. If the message freezes then shut down the game through task manager. Then rerun the exe. For me, the 'ok' button always works fine after that.

**Comment by LiRunZhe** [comment]
> > I've been facing the same issue too. I've tried every possible solution, but whenever I launch the game and the message box pops up, the game crashes after a while.😭
> 
> Try to start the game through the exe directly. If the message freezes then shut down the game through task manager. Then rerun the exe. For me, the 'ok' button always works fine after that.

I just tried repeatedly pressing the Enter key, and indeed, a few times I managed to hit the 'OK' button and successfully enter the game. However, in 90% of cases, the message box freezes, and I'm left with no choice but to wait for the game to crash. At this point, I strongly suspect that the issue lies with this message box.

**Comment by theALFA-github** [comment]
> Have you tried without DLSSTweaks?
> 
> I've never used DLSSTweaks but this mod works okay for me in Cyberpunk 2077 (although it has crashed a couple of times when launching).
> 
> All I did was:
> 
>     1. Merge the registry tweak
> 
>     2. Copy the 2 .dll files to Cyberpunk x64 directory
> 
>     3. Launch

I have tried that...Same issue happens. However, "DLSSTweaks by Emoose" works fine by itself. It ran and seemed to work fine when i first installed "DLSSTweaks by Emoose" but only after I installed "dlssg-to-fsr3 by Nukem9" the game started showing this error.

**Comment by theALFA-github** [comment]
> I just tried repeatedly pressing the Enter key, and indeed, a few times I managed to hit the 'OK' button and successfully enter the game. However, in 90% of cases, the message box freezes, and I'm left with no choice but to wait for the game to crash. At this point, I strongly suspect that the issue lies with this message box.

Tried that...didn't work. The only time I managed to get in the game after installing the  "dlssg-to-fsr3 by Nukem9", the game crashed a few secs in. Couldn't even get to the main menu. Guess gotta wait for the official update😞

**Comment by theALFA-github** [comment]
Well good news...the latest update solved the issue for me and its working great. Closing this gig😁
