### ISSUE TITLE
0.50 doesn't work on remnant 2

### ISSUE THREAD

**Issue by manafoo** [Nukem9/dlssg-to-fsr3#102]
it works for my friend he have 3070  but does not work on my rig i have 3070 ti ,no startup message for me and dlss frame generation option is not shown for me. Game is Remnant 2
my friend's RIG info " it works on his pc " : i5 13600k, 32gb ddr5 5600 ram, pcie4 m2 2tb disc, rtx 3070
my rig info : i7 8086K, 32 gb ram 3200, m.2 1tb . rtx 3070 ti
Both using windows 11

**Comment by zhangxidi1996** [comment]
> it works for my friend he have 3070 but does not work on my rig i have 3070 ti ,no startup message for me and dlss frame generation option is not shown for me. Game is Remnant 2 my friend's RIG info " it works on his pc " : i5 13600k, 32gb ddr5 5600 ram, pcie4 m2 2tb disc, rtx 3070 my rig info : i7 8086K, 32 gb ram 3200, m.2 1tb . rtx 3070 ti

Where did you and your friends put those files? I have the same problem as you.

**Comment by Nooblet16** [comment]
Yea actually I can confirm. 0.40 worked, I replaced the dlls with 0.50 and DLSS option itself disappeared.

**Comment by zhangxidi1996** [comment]
> > > it works for my friend he have 3070 but does not work on my rig i have 3070 ti ,no startup message for me and dlss frame generation option is not shown for me. Game is Remnant 2 my friend's RIG info " it works on his pc " : i5 13600k, 32gb ddr5 5600 ram, pcie4 m2 2tb disc, rtx 3070 my rig info : i7 8086K, 32 gb ram 3200, m.2 1tb . rtx 3070 ti
> > 
> > 
> > Where did you and your friend put those files? I have the same problem as you.
> 
> YourDriveHere:\SteamLibrary\steamapps\common\Remnant2\Remnant2\Binaries\Win64

thx! It works on my computer and it has startup message.Did you open the Hardware-accelerated GPU scheduling?only you first open hardware-accelerated GPU scheduling then it works

**Comment by manafoo** [comment]
> Content\Remnant2\Plugins\Shared\DLSS\Binaries\ThirdParty\Win64

yes my HAGS is on ,but game starts normally as if there is no nukem9 files , no option to enable frame generation either

**Comment by yongshen123** [comment]
> Yea actually I can confirm. 0.41 worked, I replaced the dlls with 0.50 and DLSS option itself disappeared. I'm using the Xbox store version.
> 
> EDIT: Ok I know what's happening. For some reason the nvngx_dlss.dll fine disappeared from Remnant 2\Content\Remnant2\Plugins\Shared\DLSS\Binaries\ThirdParty\Win64
> 
> putting that back in makes 0.50 work

well I also use  the Xbox store version.can you tell me how to make it work .thank you!
