### ISSUE TITLE
Not working on CP2077 epic

### ISSUE THREAD

**Issue by crfhilton** [Nukem9/dlssg-to-fsr3#109]
Did everything i could to make it work but didn't get it right... Is there something about the EpicGames edition?

**Comment by Igihara** [comment]
Works fine on the Epic version. Just look at the readme.

**Comment by Rafael01602** [comment]
don't work too in the epic Games

**Comment by Tertius76** [comment]
didn´t work for me aswell in Epic Version

**Comment by Igihara** [comment]
> didn´t work for me aswell in Epic Version
> don't work too in the epic Games

Just follow basic instructions & it will work..

![RyDeFkG7B8](https://github.com/Nukem9/dlssg-to-fsr3/assets/30577680/c510a888-fed5-415a-bbd7-c8635af256a7)

**Comment by Tertius76** [comment]
I just tried the 0.6 Version, still not wotking. I have HW Scheduling on, just copied the two files in the same directory where cyberpunk2077.exe. Merged the DisableNvidiaSignatureChecks.reg. 
Easy task, but it didn´t work.

**Comment by crfhilton** [comment]
First of all, if you did everything right and Frame Generation button is still grayed out, you have to remove/delete all files in those two folders:

C:\Program Files (x86)\Epic Games\Launcher\Portal\Extras\Overlay
C:\Program Files (x86)\Epic Games\Epic Online Services\managedArtifacts\98bc04bc842e4906993fd6d6644ffb8d
After turning on Frame Generation you will be able to notice ghosting problem around the characters in game.
Some people managed to get rid of this problem by playing around with graphics settings. However, we don't have a perfect solution yet.

Also - every time you change something in the graphic settings - restart your game. Changing graphics settings with Frame Generation enabled cause framerate drops, increased frametime, and general performance issues.

If you have any other issues or a solution for ghosting, post them below. Thanks!


This worked out for me!!
