### ISSUE TITLE
CP2077 frame gen option is gray =(

### ISSUE THREAD

**Issue by BAYdashCH** [Nukem9/dlssg-to-fsr3#112]
Hello guys! Frame gen option is gray =( 
What am I doing wrong?

Patch version 0.50
Game version 2.1 (EGS)
RTX 3080 (546.33)
REG file is applied 
Two DLL files was copied to x64 dir (without replacement)
HAGS is ON
G-sync is ON
Vsync in game is OFF
Frameless mode

![image](https://github.com/Nukem9/dlssg-to-fsr3/assets/154357398/969192b2-90e4-43fc-b324-e09b799572ed)

**Comment by xSilock** [comment]
You need to past the two files where the cyberpunk.exe is

**Comment by BAYdashCH** [comment]
> You need to past the two files where the cyberpunk.exe is

Cyberpunk2077.exe located in x64 folder. Two files was copied into the folder.

**Comment by xSilock** [comment]
Damn idk why it's not working then, It's working for me on 3080Ti

**Comment by HenriqueGomez** [comment]
Do you have Hardware-Accelerated GPU Scheduling enabled on your Windows?
![image](https://github.com/Nukem9/dlssg-to-fsr3/assets/11247187/40d98a02-be66-4b97-a7f7-359104dc7c6e)

**Comment by BAYdashCH** [comment]
> Do you have Hardware-Accelerated GPU Scheduling enabled on your Windows? ![image](https://private-user-images.githubusercontent.com/11247187/291668212-40d98a02-be66-4b97-a7f7-359104dc7c6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDc5MzcsIm5iZiI6MTcwMzAwNzYzNywicGF0aCI6Ii8xMTI0NzE4Ny8yOTE2NjgyMTItNDBkOThhMDItYmU2Ni00Yjk3LWE3ZjctMzU5MTA0ZGM3YzZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE3NDAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkMzI3ZTBjMTE2MGVkMmE1ZmYzY2RiMDBkNzNjNzM0MzUwY2FiMjBlOTZiZWE1NDdhY2Q2YzlhNzY3ZWE1NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nrRVOiqcrUSzVJCVb76fueibu9B8e0U_flfXK9mMQHc)

yes

**Comment by BAYdashCH** [comment]
I'll try this in another version of the game. From a store with 100% discounts, if you know what I mean)

**Comment by Z4ndyz** [comment]
Try the dlsstweaks version

**Comment by doktorsleepelss** [comment]
>REG file is applied

Did you apply the disable or enable reg? Need to apply the disable one, not enable if you didn't.

**Comment by artenlf** [comment]
See #55 

Please try the following:

> None of the above solutions solved my problem on base/default version of dllsg-to-fsr3
> 
> HOWEVER
> 
> It worked for me when [DLSSTweaks](https://github.com/emoose/DLSSTweaks/releases/tag/0.200.8.2l) was installed. Follow their README.md steps placing the files into x64 folder and merge the reg file. Then download the [dlssg-to-fsr3-0.41.DLSSTweaks.Edition.zip](https://github.com/Nukem9/dlssg-to-fsr3/releases/download/0.40/dlssg-to-fsr3-0.41.DLSSTweaks.Edition.zip) and place the files into x64. Overwrite files if necessary. Finally and Important!:
> 
> Don't forget to CHANGE THE PATH inside dlsstweaks.ini to the pointing inside "x64" folder to the "dlssg_dlsstweaks_wrapper.dll" file, otherwise it won't work (this is also in README.txt inside the mod .zip)
> 
> Enjoy.

**Comment by BAYdashCH** [comment]
> См. #55
> 
> Пожалуйста, попробуйте следующее:
> 
> > Ни одно из вышеперечисленных решений не решило мою проблему в базовой/стандартной версии dllsg-to-fsr3.
> > ОДНАКО
> > У меня это сработало, когда был установлен [DLSSTweaks](https://github.com/emoose/DLSSTweaks/releases/tag/0.200.8.2l). Следуйте инструкциям README.md, поместив файлы в папку x64 и объединив reg-файл. Затем загрузите [dlssg-to-fsr3-0.41.DLSSTweaks.Edition.zip](https://github.com/Nukem9/dlssg-to-fsr3/releases/download/0.40/dlssg-to-fsr3-0.41.DLSSTweaks.Edition.zip) и поместите файлы в x64. При необходимости перезапишите файлы. Наконец и важно!:
> > Не забудьте ИЗМЕНИТЬ ПУТЬ внутри dlsstweaks.ini на указатель внутри "x64" папку в папку "dlssg_dlsstweaks_wrapper.dll" файл, иначе он не будет работать (это тоже есть в README.txt внутри .zip мода)
> > Наслаждаться.

it work))) new copy of game from GOG work with base method))

**Comment by BAYdashCH** [comment]
> Что ж, похоже, мод не работает с версией EGS CP2077 (возможно, со всеми играми EGS). У меня та же проблема, в EGS CP2077 не работает генерация кадров, но в Ведьмаке 3 из стима работает.

same shit bro!)))
