### ISSUE TITLE
Add option to disable popup warning message

### ISSUE THREAD

**Issue by pedroabdenor** [Nukem9/dlssg-to-fsr3#116]
It would be good to have the option to disable the warning message after the first test. In my case, I use Steam's Big Picture with a controller away from the PC, and I always have to confirm the popup with the mouse before opening the game.

**Comment by ramonsantana** [comment]
Or maybe have the dll log first time use and not show it again after the first run

**Comment by pedroabdenor** [comment]
It was implemented in [version 0.60](https://github.com/Nukem9/dlssg-to-fsr3/releases/tag/0.60). Thanks, @Nukem9!
