### ISSUE TITLE
something wrong

### ISSUE THREAD

**Issue by atabalau** [Nukem9/dlssg-to-fsr3#140]
Hello. I send you a screenshot. The mod works fine, except what is marked in the screenshot. If I disable FrameGeneration it doesn't happen. Thank you for your effort.
![Cyberpunk 2077 (C) 2020 by CD Projekt RED 19_12_2023 17_31_01](https://github.com/Nukem9/dlssg-to-fsr3/assets/92278441/2eab91cc-afeb-485f-b60c-9eceb9c7479b)

**Comment by Nooblet16** [comment]
That's the UI layer stretching/being pulled. Pretty common issues in games that don't do half rate UI with framegen enabled. Darktide has it as well.

**Comment by atabalau** [comment]
> That's the UI layer stretching/being pulled. Pretty common issues in games that don't do half rate UI with framegen enabled. Darktide has it as well.

Okay, I got it. Thanks for the response and your work.
