### ISSUE TITLE
Jedi Survivor: Artifacts only in cutscenes

### ISSUE THREAD

**Issue by thiagofmedeiros** [Nukem9/dlssg-to-fsr3#154]
It works great on Jedi Survivor, but when any cutscene begins, the artifacts go crazy, but it stops when in normal gaming.

RTX 3090 TI
HDR ON
DLSS Quality
Ray Tracing ON

**Comment by MarcoReckless** [comment]
Did you try if it does the same without HDR (which isn't supported as far as I know)?

**Comment by thiagofmedeiros** [comment]
I solved it removing the letterbox with

https://github.com/Lyall/JediSurvivorFix
