### ISSUE TITLE
nVidia DLSS Super Resolution disappears from MSFS2020

### ISSUE THREAD

**Issue by pedrospinto** [Nukem9/dlssg-to-fsr3#161]
It's causing "nVidia DLSS Super Resolution" to disappear from MSFS's anti-aliasing options. I do get it back after dlssg-to-fsr3 removal.
Win11 running driver 546.29 on a RTX3090 and, yes, HAGS on, in-game vsync off. Tried builds 0.50 and 0.60, with and without DLSSTweaks.

**Comment by Nooblet16** [comment]
Check if the DLSS dll exists, if DLSS disappears it's because the nvgnx_dlss.dll is missing.

**Comment by pedrospinto** [comment]
That was it, thanks!
