### ISSUE TITLE
This work with AMD RX gpus?

### ISSUE THREAD

**Issue by rpf16rj** [Nukem9/dlssg-to-fsr3#162]
Hi, great work, thats amazing.

I'm confusing, the feature FSR3 from AMD doesn't work with AMD RXs GPUs?

I'm trying with Cyberpunk 2077 with a RX 6660 XT but the DLSS doesn't available to turn on.

**Comment by YarsGames** [comment]
Work only with RTX 2000 and 3000 series.

**Comment by ImASadBoy** [comment]
Nukem said it everywhere in the page and in download files, it replaces DLSSFG with FSR3 FG, but still uses DLSS as an Upsclaer, it requires and RTX GPU because it requires the DLSS pipeline to work, the game won't even show DLSS options if you don't have an RTX GPU

**Comment by Igihara** [comment]
> LOL. If only that were true. NVIDIA is actually several times worse than AMD, regarding "sharing" technology. I will like to know where is the Open Source participation from them for:
> 
> NVIDIA Physx NVIDIA DLSS 2, 3, 3.5 NVIDIA Hair NVIDIA G-SYNC NVIDIA CUDA.
> 
> Whereas all of the similar technologies coming from AMD are Open Source already. Stop spreading nonsense.

https://github.com/NVIDIAGameWorks/PhysX
https://github.com/NVIDIA/DLSS
https://developer.nvidia.com/content/nvidia-hairworks-tools-released
https://developer.download.nvidia.com/compute/cuda/opensource/
