### ISSUE TITLE
Crashing with 0.60 

### ISSUE THREAD

**Issue by HayTTG** [Nukem9/dlssg-to-fsr3#169]
Sudden crashing which wasn't apparent before since the update

**Comment by Vladzor87do** [comment]
![image](https://github.com/Nukem9/dlssg-to-fsr3/assets/63660560/7d773f3f-e81e-4400-838a-5ded38a35fec)

**Comment by Styphoryte** [comment]
Lmao dude didn't even specify what game at the very least...
