### ISSUE TITLE
[FEATURE REQUEST]: Support for Nvidia RTX Remix Games

### ISSUE THREAD

**Issue by n3thshan** [Nukem9/dlssg-to-fsr3#180]
Is able to load the dll into the Portal RTX as evidenced by the pop up message however, the option to enable frame generation does not appear in the Nvidia RTX Remix Overlay. Would be great to see this implemented as Half Life 2 will be another RTX Remix game a lot of gamers are anticipating to play on their ampere/turing cards. Thank you!

**Comment by Z4ndyz** [comment]
https://github.com/Nukem9/dlssg-to-fsr3/issues/141

Read more about this here

**Comment by n3thshan** [comment]
Closing this issue since it's been adressed in #141
