### ISSUE TITLE
RTSS FPS limit causes lag?

### ISSUE THREAD

**Issue by miyazonoyuzuki** [Nukem9/dlssg-to-fsr3#182]
I applied this mod and working wonderfully but it forces the gpu to run at 100% with unlocked frame rates. 
Normally I'd limit FPS in RTSS but it causes lag and stuttering and nvidia control panel fps limit also not working. 
Cyberpunk's own FPS limiter is also not working.
I just want to lock FPS to a reasonable limit at all times with this mod. How do I do that?

**Comment by guillenxd** [comment]
Do you have a monitor with gsync or freeSync?

**Comment by Z4ndyz** [comment]
For FG do not use rtss limiter or ingame they'll lead ro abnormal behaviour use only nvidia control panel limiter

**Comment by miyazonoyuzuki** [comment]
thank you guys. I'll try again with Nvidia CP only
My monitor is freesync.

**Comment by Styphoryte** [comment]
I thought the newest 4.6.5 beta of RTSS has FG fps limit support from what I've heard but do your own research because I could definitely be wrong about that... I hadn't even realized my RTSS version was so old. (4.6.3 I think). I am trying an FPS limit of 57 on RTSS in Cyberpunk with DLSSG to FSR3 so I will see how it goes. 

Currently my big problem now is the input latency this mod seems to introduce, and I've made sure v-sync is off in-game as well as G-sync is setup trough Nvidia Control panel and manually enabled V-sync as well.

**Comment by guillenxd** [comment]
> Por lo que he oído, pensé que la nueva versión 4.6.5 beta de RTSS tiene soporte para límite de fps FG, pero investiga por tu cuenta porque definitivamente podría estar equivocado en eso... Ni siquiera me había dado cuenta de que mi versión RTSS era tan antigua. (4.6.3 creo). Estoy probando un límite de FPS de 57 en RTSS en Cyberpunk con DLSSG a FSR3, así que veré cómo va.
> 
> Actualmente, mi gran problema es la latencia de entrada que este mod parece introducir, y me he asegurado de que v-sync esté desactivado en el juego y de que G-sync esté configurado a través del panel de control de Nvidia y también haya habilitado V-sync manualmente.

Could you tell me how you measure the latency? 🥹

**Comment by Styphoryte** [comment]
> > Por lo que he oído, pensé que la nueva versión 4.6.5 beta de RTSS tiene soporte para límite de fps FG, pero investiga por tu cuenta porque definitivamente podría estar equivocado en eso... Ni siquiera me había dado cuenta de que mi versión RTSS era tan antigua. (4.6.3 creo). Estoy probando un límite de FPS de 57 en RTSS en Cyberpunk con DLSSG a FSR3, así que veré cómo va.
> > Actualmente, mi gran problema es la latencia de entrada que este mod parece introducir, y me he asegurado de que v-sync esté desactivado en el juego y de que G-sync esté configurado a través del panel de control de Nvidia y también haya habilitado V-sync manualmente.
> 
> Could you tell me how you measure the latency? 🥹

You will need MSI Afterburner newest version and also RTSS 4.6.5 beta as well. Once you've got those installed then open MSI after burner which also should open Riva tuner (RTSS). Then open your setting in MSI afterburner go to Monitoring tab and scroll all the way down to Frametime and make sure you have it checked to show in OSD. Also do this for Framerate, GPU1 usage, Gpu1 TEMP,  GPU1 memory usage, CPU temperature, CPU Usage. And any other you want! Then go to RTSS and make sure at the top on screen display is enabled. On the right side you can change where your OSD is positioned in-game as well. I usually prefer the top right hand side but that's just me sometimes it's better to change it depending on the game which you can also specify by adding an .exe and changing the setting per .exe's as well. Now you must also setup a hotkey to Toggle OSD on and off. You must also do this in MSI afterburner, go to settings again and then On screen display tab. Then you can set your desired hot keys there. I use Ctrl + \
