### ISSUE TITLE
The Witcher 3 frame gen doesn't work 

### ISSUE THREAD

**Issue by phourior** [Nukem9/dlssg-to-fsr3#186]
I add these file to The Witcher 3's directory(The Witcher 3\bin\x64_dx12\), but it seems not working as the frame gen option keeps grey and no warning signs when I start the game. I tried dlsstweaks version but dlss was disabled after dlsstweaks installed. I use 13600kf+3080, V-sync OFF and hardware acceleration ON and the game is on Steam.

**Comment by neverever124** [comment]
strange it works for my laptop rtx3060 without a problem. Maybe try verifying the game integrity in Steam and try the normal version. I play with dlss quality on 1080p

**Comment by Aidorin0** [comment]
Be sure to use the last game version (4.04). It didn't work in v4.01 for me. I've updated to 4.04 and now the FG option is unlocked and It works fine.
