### ISSUE TITLE
REMNANT 2 ULTIMATE EDITION NOT WORKING. Unreal engine exe version 5.2.1.0. RTX 3060 12 GB OC.

### ISSUE THREAD

**Issue by Asif7573** [Nukem9/dlssg-to-fsr3#188]
I tried all the possible ways to make it work with Remnant 2 on Steam or Epic, but no luck. It works in Robocop perfectly. But the Robocop exe file version is based on Unreal Engine 5.2.0.0. And Remnant 2 is 5.2.1.0.
I have also tried replacing all the DLSS files in Remnant 2 with Robocop DLSS files, but it is not working.

**Comment by manafoo** [comment]
where are you putting the files in remnant 2 ?
it should be inside SteamLibrary\steamapps\common\Remnant2\Remnant2\Binaries\Win64

**Comment by Asif7573** [comment]
> where are you putting the files in remnant 2 ? it should be inside SteamLibrary\steamapps\common\Remnant2\Remnant2\Binaries\Win64

Yes. It does not work just by putting the dll files in Win64 for Remnant 2. But I made it work tonight by installing DLSS tweaker and changing the directory path of DLSS. Now it is working perfectly. But the procedure is hard. And everybody will not be able to figure it out. You have to change the path of DLSS as well as DLSSG in the override path.

**Comment by viahes** [comment]
It works fine non DLSS tweaker version and Remnant 2 on Steam.

**Comment by manafoo** [comment]
> onight by installing DLSS tweaker and changing the directory path of DLSS. Now it is working pe

i think the reason of that lies somewhere in the registery ,but it is working for most people without the tweaker. 
also side note , make sure that you dont have gpu preference in the windows graphics settings

**Comment by Asif7573** [comment]
> It works fine non DLSS tweaker version and Remnant 2 on Steam.

It is working with the standard version but not with the ultimate version of Steam. For some reason, it fails to work on Windows 11 Insider Beta. I have also acquired ownership of the complete folder, but with no luck.
@manafoo is probably right. It has to do something with the registry.

**Comment by RogueMo92** [comment]
> > where are you putting the files in remnant 2 ? it should be inside SteamLibrary\steamapps\common\Remnant2\Remnant2\Binaries\Win64
> 
> Yes. It does not work just by putting the dll files in Win64 for Remnant 2. But I made it work tonight by installing DLSS tweaker and changing the directory path of DLSS. Now it is working perfectly. But the procedure is hard. And everybody will not be able to figure it out. You have to change the path of DLSS as well as DLSSG in the override path.

so you made it work with the ultimate edition but it took you more time? if so, can you explain how?

**Comment by RogueMo92** [comment]
> It works fine non DLSS tweaker version and Remnant 2 on Steam.

standard edition or ultimate ?

**Comment by viahes** [comment]
> > It works fine non DLSS tweaker version and Remnant 2 on Steam.
> 
> standard edition or ultimate ?

Ultimate edition

**Comment by Akentrus** [comment]
Hi, the option for frame gen appears for me but it does not affect fps/latency or any stats it just does nothing for me anyone else may got this issue?
