### ISSUE TITLE
More than 1 generated frame ?

### ISSUE THREAD

**Issue by Panjaksli** [Nukem9/dlssg-to-fsr3#189]
Debug display with only generated frames looks much better than expected in CP2077.
Do you think it would be possible to generate more than 1 frame in between 2 real frames ? At least for experimenting :)

**Comment by cichy45** [comment]
How can you enable debug frames only?

**Comment by MarcoReckless** [comment]
> How can you enable debug frames only?
Downloads the Developer Debug Configuration off NexusMods, place it in the same directory as the DLLs and then edit it, set 'EnableInterpolatedFramesOnly' to '1'.

**Comment by HayTTG** [comment]
> Downloads the Developer Debug Configuration off NexusMods, place it in the same directory as the DLLs and then edit it, set 'EnableInterpolatedFramesOnly' to '1'.

Do you have a link to that?

**Comment by cichy45** [comment]
@HayTTG 
Developer Debug Configuration
https://www.nexusmods.com/site/mods/738?tab=files

**Comment by Nukem9** [comment]
In theory the interpolation algorithms support multiple frames generated between two real frames. In reality FSR 3 and DLSS-G don't support it. So no, not possible.
