### ISSUE TITLE
MSFS stuttering and Overlay Windows such as ATC distortion

### ISSUE THREAD

**Issue by Avidean** [Nukem9/dlssg-to-fsr3#194]
Thanks for bring FG to all RTX cards. I've install everything and setup as described and installed latest Nvidia Drivers. The mod works as expected but for the stutters and MSFS overlay shimmering. I'm sure both observed problems is actually one problem because both issues go away if I change the refresh rate to 30hz instead of 60hz. My hardware 3090 + i9 10900K at5.2ghz. On the Avsim forum many users have reported this issue while on the other hand many with the same hardware or close too it as mine have reported that they don't have this issue. The issues seems to only occur when panning with the mouse or TrackIR. A video speaks a thousand words: https://youtu.be/d5qm9amQVkQ

Any ideas as to what's causing it?

Thanks in advance

**Comment by guillenxd** [comment]
> Gracias por llevar FG a todas las tarjetas RTX. Instalé todo y configuré como se describe e instalé los últimos controladores de Nvidia. El mod funciona como se esperaba, excepto por los tartamudeos y la superposición de MSFS que brilla. Estoy seguro de que ambos problemas observados son en realidad un solo problema porque ambos problemas desaparecen si cambio la frecuencia de actualización a 30 Hz en lugar de 60 Hz. Mi hardware 3090 + i9 10900K a 5,2 ghz. En el foro de Avsim, muchos usuarios han informado de este problema, mientras que, por otro lado, muchos con el mismo hardware o cerca del mío han informado que no tienen este problema. Los problemas parecen ocurrir solo al desplazarse con el mouse o TrackIR. Un vídeo habla más que mil palabras: https://youtu.be/d5qm9amQVkQ
> 
> ¿Alguna idea sobre qué lo está causando?
> 
> gracias de antemano

how do you change the refresh rate?

**Comment by Nukem9** [comment]
This artifacting happens when games don't supply a HUD-less color buffer. FSR's optical flow analysis incorrectly picks up HUD elements as being part of the game world and tries to interpolate them.

If you want to do me a favor, [place this INI file next to the DLL](https://raw.githubusercontent.com/Nukem9/dlssg-to-fsr3/master/resources/dlssg_to_fsr3.ini), run the game, and then screenshot or record the results.

**Comment by Avidean** [comment]
If I click on the link I get this text: 
[Debug]
EnableDebugOverlay=1
EnableDebugTearLines=1
EnableInterpolatedFramesOnly=0

I have no idea how to add that to the DLL.

If you can give me some instructions I'll certainly do it.

Thanks

**Comment by Avidean** [comment]
OK I think you mean paste it at the bottom of dlssg_to_fsr3.text
I'm just doing it now. What harm can it do if I'm wrong? 😂

**Comment by Avidean** [comment]
Look like that worked! I'm doing a test flight now which I'll record.

**Comment by lamiska** [comment]
Create and paste it into dlssg_to_fsr3.ini

**Comment by lamiska** [comment]
@Nukem9 Screenshots with ini file you have sent:
![Screenshot (1)](https://github.com/Nukem9/dlssg-to-fsr3/assets/12211787/7a698330-b05b-41a1-84c5-50c872fa5320)
![Screenshot (2)](https://github.com/Nukem9/dlssg-to-fsr3/assets/12211787/c15e93a9-ccf6-4b34-a45a-81ecb8d8c2d1)

**Comment by Avidean** [comment]
OK, I think what @lamiska Is what you are asking for. No?

**Comment by Guenseli** [comment]
Just join here because I have a similar problem in MSFS.
It is not when having overlying panels. But when I'm on very demanding ground sceneries (e.g. Frankfurt)
I have then the issue that the planes cockpit is ok, but everything outside the window gets distorted as in the video above.

Otherwise, it is really, really great. never had such a fluid and smooth experience with my 3080.
Hope it could get optimized for MSFS
thank you!!

**Comment by Sousaboi** [comment]
I too have this issue but it is way worse.. [https://www.youtube.com/watch?v=7DDqyzGaaIA](url)

**Comment by Sousaboi** [comment]
Just tried older versions of this mod, tried using the dll tweak thing, I have changed everything imaginable and it is still doing the same as the video I sent earlier....

**Comment by Nukem9** [comment]
MSFS requires a manual fix from my side. FSR 3 FG doesn't handle all cases DLSS-G can. No amount of settings tweaks will fix it. No ETA.

> This artifacting happens when games don't supply a HUD-less color buffer. FSR's optical flow analysis incorrectly picks up HUD elements as being part of the game world and tries to interpolate them.

**Comment by Sousaboi** [comment]
Is there a fix for it? I do not understand..

**Comment by Avidean** [comment]
For what its worth at 23 and 29 hz its works spectacularly. Even after its fixed I will probably continue to use it this way. Apart from the ghosting of the overlays at 50hz or 60hz it also stutter on due to FPS dropping below target even with a 3090 duo to 100% GPU load as reported by RTSS. Granted this at maxed out setting in KLAX with loads of traffic. However, at 29hz there are no stutters at 30fps in scenarios where the FPS would be only about 20fps (the GPU on needs to render 15fps to get 30 with FG on with this mod) Doesn't sound great. Right? However, for anyone using a 4KTV for display with the TV's built in frame interpolation on you get 60fps on screen from the 30 you get from the GPU. So 60 fps from 15fps rendered! I was told this wouldn't work when I thought about it first before I had FG. But it does! It's spectacular! not only does it work at 29hz it even works at 23hz and jsut as well and perhaps it look even better. So that's about 50fps on screen for 12fps rendered.! So this MOD is massive winner for me. Thanks for making it. If you have a Samsung 4KTV or can borrow one (they are very common) I would strongly recommend try this.

**Comment by Sousaboi** [comment]
So it seems like I should change my monitor refresh rate to 30 hz?

**Comment by Avidean** [comment]
If you monitor supports 30hz then try it. If you are used to 30fps then you should have an Improvement. Plus you gain overhead getting 30fps with FG vs without it. But the real magic only occurs if you are using a TV with frame interpolation for display rather then a computer monitor. The TV's Frame interpolation will take the 30fps its getting from the GPU and turn it into 60fps.

**Comment by Sousaboi** [comment]
So it seems I need to change my monitor refresh rate to 30 hz?

**Comment by Sousaboi** [comment]
Well I just attempted to do that, my monitor cannot go below 50 hz..

**Comment by Avidean** [comment]
Well that's as good as its gonna get for you then. 50hz is better than 60hz for MSFS with this FG MOD if it gets fixed because the load on your hardware will be less and you'll have a better chance of getting 50fps out of you GPU than 60 and I don't think anyone can really tell the difference between 50 and 60. When and if it works my 4KTV will take the 50 and turn it into 100. That is the big advantage of using a modern TV over a monitor for MSFS. A large range of compatible refresh rates and Frame interpolation. Plus you can watch telly on it!

**Comment by Sousaboi** [comment]
Ah okay. I still have very high hopes for this mod too, as it has only been out for a week now! Plenty of time to fix it up!

**Comment by Sousaboi** [comment]
Okay Im sorry for this question and my impatience but @Nukem9 are you currently working on a fix for this issue?

**Comment by Sousaboi** [comment]
Issue still persists on v .0.80

**Comment by Avidean** [comment]
Thanks for this @Nukem9 much appreciated. It will be of great value to MSFS players on 2 and 3000series RTX cards and I say that there is a hack somewhere to make it work on 1000series GTX cards. It benefits everyone and once they figure out how it benefits them on there particular system and stop trying to get 60fps with Maxed out setting they should be happy.  😂 hopefully you can improve it in the weeks and months ahead. Its a winner for me!
