### ISSUE TITLE
Unfortunately it doesn't work with 3060TI

### ISSUE THREAD

**Issue by fliegeroli** [Nukem9/dlssg-to-fsr3#195]
Unfortunately it doesn't work for me in RTX 3060TI in MSFS2020. My entire RAM 32GB is full and my Graphics memory is 8GB and then I have 20 fps. It's a shame. I did everything as described.

**Comment by Avidean** [comment]
Try setting your refresh rate to 30hz and see what happens

**Comment by fliegeroli** [comment]
Do you mean the refresh rate in the game at 50%?

**Comment by Avidean** [comment]
In the Nvidia Control Panel you can set the refresh rate of your display to 30hz if its in the drop down list under change resolution. If its not forget about it. If it is go ahead a try it and run MSFS at 30hz leave everything else as is. do you use a TV or a monitor for display?

**Comment by fliegeroli** [comment]
Unfortunately I can only select 60, 59 or 50 Hz in the selection menu. I have a monitor.

**Comment by Avidean** [comment]
OK sorry I cant help you then. I am getting good results at 30hz but find it doesn't work very well above that.

**Comment by fliegeroli** [comment]
OK. Thanks anyway. I don't understand why the memory is running so full.

**Comment by mcdgray129** [comment]
I honestly dont understand why you would want to lock yourself to 30hz and i couldnt even possibly see that as a solution for a fix.
I also dont have a fix for you but i own a 3060ti and its working perfect for me.

**Comment by fliegeroli** [comment]
I found the problem. It's called: Geforce Experience. As soon as I select a filter, the entire memory runs full and the frames go down and it's no longer playable. So for anyone where it doesn't work, turn off Experience ;-)
