### ISSUE TITLE
Help simply doesn't work 

### ISSUE THREAD

**Issue by DrRevenge** [Nukem9/dlssg-to-fsr3#198]
so I have been trying for days but nothing first I tried in Cyberpunk but I don't get notification and option is grayed out (I followed the steps exactly) than I try Witcher 3 there I get notification but FG is grayed out. I tried with all versions. HAGS is turned on, and today when I tried again I don't even get the notification on Witcher 3 anymore I just don't no what to please can someone help.

**Comment by manafoo** [comment]
first of all do you have a RTX card ? meaning 2000+ series? 
also if you set choose specific gpu via settings>>>system>>display>>graphics. 
remove those settings that you specified , press remove , if removing is not possible , select let windows decide

**Comment by DrRevenge** [comment]
I managed to fix it by deleting some epic games folders thanks anyway
