### ISSUE TITLE
Debug screens in 0.7 using Developer Debug Configuration (CP2077)

### ISSUE THREAD

**Issue by leckisnm** [Nukem9/dlssg-to-fsr3#199]
I read in another issue that the game looked better by downloading Developer Debug Configuration and editing "EnableInterpolatedFramesOnly" to "1"

![developer](https://github.com/Nukem9/dlssg-to-fsr3/assets/97215771/f7446a47-8eed-4537-b8f3-18f9f4cb94d2)

well, my problem is that when playing six small screens appear

![debug](https://github.com/Nukem9/dlssg-to-fsr3/assets/97215771/e33c0d81-fa7f-43e7-91c9-61346f7362ea)

I saw that it was already solved but it was with an old version and without the Developer Debug Configuration being the problem
Does anyone know how to solve it?

**Comment by leckisnm** [comment]
I already solved it, I just had to edit the value of "EnableDebugOverlay" and "EnableDebugTearlines" to "0", my bad

**Comment by LeoBello00** [comment]
i don't think the game will look better with that option set to 1 xD
