### ISSUE TITLE
Cyberpunk 2077 hogs a lot of RAM

### ISSUE THREAD

**Issue by itsequal** [Nukem9/dlssg-to-fsr3#232]
Cyberpunk 2077 starts consuming RAM like crazy from the loading cinematics, general RAM usage jumps from 9 GB to 30GB before even reaching the main menu

**Comment by Erebus1245** [comment]
> Cyberpunk 2077 starts consuming RAM like crazy from the loading cinematics, general RAM usage jumps from 9 GB to 30GB before even reaching the main menu


I can not confirm this it uses about 4-5 GB as always for me and i don't see why this mod should even increas ram usage vram sure but ram?
Check your mods and clean reinstall the game without it to me this sounds like something is causing a memory leak, and looking it up online reveals there are many reports of a memory leak happening since 2.0/PL dropped and even before that so it's most likely a bug in the game causing it.

**Comment by Dravic** [comment]
Does not sound like this mod is causing your issue, to be honest.

**Comment by itsequal** [comment]
> Does not sound like this mod is causing your issue, to be honest.

Tried the game without the mod and max RAM does't exceed 16GB, only with the mod it jumps to 30GB, but I'll try reinstalling the game and the mod

**Comment by EdLovecraft** [comment]
No problems for me, no huge difference in RAM usage, using this mod even lowered my CPU usage and made my CPU temperature lower

**Comment by Igihara** [comment]
Nothing to do with the mod.

**Comment by itsequal** [comment]
Reinstalled full game from Steam, without the mod, RAM usage sits at 16GB - 17GB, with the mod and activating the Frame Generation option, RAM gradually increases up to your maximum available, if the option is disabled, the RAM stops increasing. I've only seen this problem in Cyberpunk 2077 but I will try to reproduce it in other games

Rig Specs:
Ryzen 5 5600x
RTX 3080 10GB 
32GB Ram 3200 Mhz
Windows 10
Pagefile: 20GB

**Comment by itsequal** [comment]
Downgraded drivers from 546.17 to 537.58 and no more memory leaks, everything running smooth as butter, RAM usage sticks to 16GB-17GB

**Comment by itsequal** [comment]
EDIT 2:

I've identified the memory leak and the cause might be the NVIDIA Freestyle filters, specifically the Color filter; if facing this problem, try disabling all the filters first
