### ISSUE TITLE
Game becomes a stuttery mess when running on a 1440p display.

### ISSUE THREAD

**Issue by Weather-OS** [Nukem9/dlssg-to-fsr3#241]
This issue only occurs when I set the game resolution to 1440p. 1080p works just fine with FSR 3 FG Enabled.
Game in question: Ratchet & Clank: Rift Apart.
GPU: NVIDIA GeForce RTX 3060 LHR.
CPU: Intel Core i7 8700K (5.2 GHz OC)

**Comment by ImASadBoy** [comment]
> This issue only occurs when I set the game resolution to 1440p. 1080p works just fine with FSR 3 FG Enabled. Game in question: Ratchet & Clank: Rift Apart. GPU: NVIDIA GeForce RTX 3060 LHR. CPU: Intel Core i7 8700K (5.2 GHz OC)

What settings and what mod version?

**Comment by Weather-OS** [comment]
This happens with every game config I tried. Using FSR Upscaling made it even worse. The only config that made this stuttering go away is setting my display resolution to 1080p which is something I'd rather not do.

**Comment by ImASadBoy** [comment]
> This happens with every game config I tried. Using FSR Upscaling made it even worse. The only config that made this stuttering go away is setting my display resolution to 1080p which is something I'd rather not do.

But what is your base framerate at 1440p in those games without FG? Amd recommends at least 60FPS for turning on FG.

**Comment by Weather-OS** [comment]
DLSS Set to Ultra performance, The FPS without FG is 80 but with FG it still stutters like hell

**Comment by ImASadBoy** [comment]
> DLSS Set to Ultra performance, The FPS without FG is 80 but with FG it still stutters like hell

Have you tried not using Ultra Performance? That was made specifically for 8k resolution and the internal rendering resolution is so low it can cause problems:
33% of 1440p is 480p

**Comment by Weather-OS** [comment]
DLSS Q With the game set to lowest preset, it still lags a lot. 60 ish FPS without FG

**Comment by Weather-OS** [comment]
Managed to somewhat fix it. Somehow turning on HDR Eradicates this issue for whatever strange reason.

Also while we are on topic, Why is there SO MUCH input lag? I mean I've turned on AMD Anti Lag and NVIDIA Reflex + Boost and the input lag is still considerably high

**Comment by Weather-OS** [comment]
Oh wait, The reason HDR makes this issue go away, is that frames aren't being interpolated anymore. Now I'm just left confused

**Comment by Weather-OS** [comment]
I still haven't fixed this issue yet.

One janky workaround is to use AMD's RSR but I'd rather not do that.
I may patch this mod to automatically detect such config and to only interpret frames at 1080p as a workaround as well.

**Comment by TimmyP777** [comment]
3060 too weak of a card to see the benefits even a 3060ti will get.

**Comment by Weather-OS** [comment]
Wait, if it's "too weak", Then what's this? https://www.youtube.com/watch?v=YuEC4-sZgkY

**Comment by bonitinhokun** [comment]
this config to weak to 1440p, you can try to check v-sync on game options and nvidia control panel, try to force it to fast on control panel or low the graphics idk, also rift apart is messed up

**Comment by Weather-OS** [comment]
I managed to fix this by running the game on Linux instead.
says a lot about windows gaming performance doesn't it?

**Comment by TimmyP777** [comment]
You have a 3060. Its not a 1440p card no matter what pcmr feeds you. They are not a helpful community, as they are not very knowledgeable in general.

A 3060 is too weak for 1440p in modern games,  and actually should have been called the 3050ti due to how much weaker it is than the 3060ti... which is the card where this mod really starts to shine.

**Comment by Weather-OS** [comment]
I mean with FSR 3 in R&C I get about 80 FPS and it barely stutters so I can't really complain.

**Comment by Weather-OS** [comment]
Here's a quick demo if anyone's interested: https://www.youtube.com/watch?v=ZO93rO3bSWA
