### ISSUE TITLE
X1 Precision crashes mod

### ISSUE THREAD

**Issue by elniunio** [Nukem9/dlssg-to-fsr3#244]
CPU 11700kf @5GHz, RAM 64GB @3600MHz, oc dual rtx 3090 via NVlink works like a charm with the mod on Witcher3 and CP2077. The only problem I have are crashes caused by X1 Precision which I use for RGB, power mgmt and monitoring. It would be nice to add X1 Precision compatibility to the mod.

**Comment by Igihara** [comment]
Waste of time & resources to add compatibility to something like that.

**Comment by elniunio** [comment]
anyway I moved to Afterburner, which works
