### ISSUE TITLE
This guy run Frame Generation on a GTX card. All this years NVIDIA was lying to us.

### ISSUE THREAD

**Issue by Or0b0r0s** [Nukem9/dlssg-to-fsr3#250]
https://www.youtube.com/watch?v=0ooUoJvUOi0&ab_channel=EDWARDGaming

**Comment by Z4ndyz** [comment]
Remember we're using AMD software based fsr3 frame generation, nvidia's framegen relies on their tensor and ofa hardware cores and that at the very best be enabled only from 2000 rtx series upwards since the gtx series doesmt not have any tensor or ofa cores

**Comment by Or0b0r0s** [comment]
> Remember we're using AMD software based fsr3 frame generation, nvidia's framegen relies on their tensor and ofa hardware cores and that at the very best be enabled only from 2000 rtx series upwards since the gtx series doesmt not have any tensor or ofa cores

GTX is able to run the mod, so why you keep lying ?

**Comment by Z4ndyz** [comment]
Because this guy first of all is using LukeFz's FSR2 to FSR3 FRAME GEN MOD he is not using DLSSG2FSR3FG mod also why you jump and accuse people of lying after i gave you a nice explanation do you think i'm an nvidia seller or what jesus christ some people are hellbent on fighting on the internet
Also if you would have read the description in his video with a bit of knowledge you have noticed all of these, he is running FSR technologies only he is using a completely different mod than this

**Comment by Or0b0r0s** [comment]
> Because this guy first of all is using LukeFz's FSR2 to FSR3 FRAME GEN MOD he is not using DLSSG2FSR3FG mod also why you jump and accuse people of lying after i gave you a nice explanation do you think i'm an nvidia seller or what jesus christ some people are hellbent on fighting on the internet Also if you would have read the description in his video with a bit of knowledge you have noticed all of these, he is running FSR technologies only he is using a completely different mod than this

Somehow now we have a nice explanation about this case, thank you.

**Comment by kedaitinh12** [comment]
For LukeFZ 0.7.2 you can use here
https://drive.google.com/file/d/1-vgQPeIk_7wpgjiqqiqmoQUlrvDi0X6F/view?usp=drivesdk

And read here to know what file to use. Read redme in file download to know how to mod
https://docs.google.com/spreadsheets/d/1bGDjgkRahwNvD2XtqiHdZBRc6VB52UKsr1Qn1TmvSHo/edit#gid=0

**Comment by VCery1108** [comment]
There is a video on youtube that works with GTX10xx card by using dummy's nvapi64.dll and dlssg-to-fsr3 mod.
