### ISSUE TITLE
witcher 3 next gen patch 4.04 crash when rotating the camera too fast

### ISSUE THREAD

**Issue by Erebus1245** [Nukem9/dlssg-to-fsr3#263]
I discovered an easily reproducible bug while playing The Witcher 3 next gen patch 4.04. When I turn on frame-generation and rotate the camera at a fast speed the game freezes and crashes with an error after a few seconds.

**Comment by Dravic** [comment]
Same issue here:

https://github.com/Nukem9/dlssg-to-fsr3/issues/145

I confirm.

**Comment by Dampfinchen** [comment]
There are also some latency issues with it. First start is very laggy, then it feels good and after that it gets laggy again.

**Comment by Erebus1245** [comment]
> There are also some latency issues with it. First start is very laggy, then it feels good and after that it gets laggy again.

Doesn't really happen to me and sounds like your base frame rate is just too low.

**Comment by Dampfinchen** [comment]
> > There are also some latency issues with it. First start is very laggy, then it feels good and after that it gets laggy again.
> 
> Doesn't really happen to me and sounds like your base frame rate is just too low anyway it has nothing to do with the issue at hand.

Nah. Otherwise the latency would always be high, but that isn't the case. From one moment to the next it feels smooth and then laggy again.

I've not encountered that issue in Cyberpunk with the same base framerate.

**Comment by Dravic** [comment]
Appears to be fixed after briefly testing release version 0.8.1!

**Comment by Erebus1245** [comment]
Can confirm it's fixed

**Comment by Erebus1245** [comment]
Can confirm it's fixed
