### ISSUE TITLE
how to put the mod into dying light 2 and spiderman remastered??

### ISSUE THREAD

**Issue by juhannnnnn** [Nukem9/dlssg-to-fsr3#269]

**Comment by Igihara** [comment]
Follow the basic instructions that have been outlined for you.

**Comment by juhannnnnn** [comment]
> Follow the basic instructions that have been outlined for you.

i have followed those but it still doesnt work

**Comment by peter1599** [comment]
You cant. Dying Light 2 have extra checks for Frame Genreation support.

**Comment by ImASadBoy** [comment]
I've tried basically everything for dying light, even forcing FG on from files but it doesn't work

**Comment by juhannnnnn** [comment]
what about spiderman remastered anyone??


> I've tried basically everything for dying light, even forcing FG on from files but it doesn't work



> You cant. Dying Light 2 have extra checks for Frame Genreation support. Im currently trying to lets say "unlock it" by modifying game .dll(s) but im very slow with it. So far unlocked the option for frame gen but even when I turn it on, it doesnt works. So there might be more checks.
> 
> ![292876314-3509fd83-8c64-450e-8263-4533b4e774b9](https://private-user-images.githubusercontent.com/25458870/293089582-aa9f6b14-d4b8-4c35-a801-c4ee93889e29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NDQ1MDAsIm5iZiI6MTcwMzc0NDIwMCwicGF0aCI6Ii8yNTQ1ODg3MC8yOTMwODk1ODItYWE5ZjZiMTQtZDRiOC00YzM1LWE4MDEtYzRlZTkzODg5ZTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDA2MTY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyMTcyNzk4MWE3YzI1NzFkNTAzMzhlNWRjYThhYmE4Njg0NDc1ODQ0MWVlOWI5ZTljMTk2NTRiOTIyZTk2NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AW4TzyKF1HvXpUo6oZWf7cxpQngOyTwq2hemmu8J3iE)

**Comment by ImASadBoy** [comment]
@peter1599 check the wiki, I made it! https://github.com/Nukem9/dlssg-to-fsr3/wiki/Dying-Light-2

**Comment by peter1599** [comment]
@ImASadBoy 

Not works.

I tried this version dll before.

**Comment by ImASadBoy** [comment]
> @ImASadBoy
> 
> Not works.
> 
> I tried this version dll before.
> 
> No framegen option.
> 
> nvm. The dll you linked works. Did you modfiy that? If yes what did you change?

You need all 3, the DLSSTweaks, DLSSG-TO-FSR3 and version.dll. I updated the version.dll from the original repository to expand the compatibility with games and changed the architecture.

**Comment by peter1599** [comment]
@ImASadBoy Do you have discord?

**Comment by ImASadBoy** [comment]
> @ImASadBoy Do you have discord?
What do you need tho? If possible it would be cool to solve this here

**Comment by peter1599** [comment]
@ImASadBoy I just wanna know what did you change cause I also have a modified version of that dlssspoofer with changed architecture but for me that didnt worked.

**Comment by ImASadBoy** [comment]
> @ImASadBoy I just wanna know what did you change cause I also have a modified version of that dlssspoofer with changed architecture but for me that didnt worked.

I'll fork it on GitHub from the original repository as soon as I have a little bit of time.

**Comment by deveers** [comment]
> @peter1599 check the wiki, I made it! https://github.com/Nukem9/dlssg-to-fsr3/wiki/Dying-Light-2

doesn't work for me, game crashes after loading a save

**Comment by peter1599** [comment]
As I said I just changed architecure. 

On the discord part I understand but would been easier to talk there about this instead in github comments.

Forking would be great, ye and thanks.

**Comment by ImASadBoy** [comment]
> As I said I just changed architecure.
> 
> On the discord part I understand but would been easier to talk there about this instead in github comments.
> 
> Forking would be great, ye and thanks.

give me your discord @

**Comment by peter1599** [comment]
> > As I said I just changed architecure.
> > 
> > On the discord part I understand but would been easier to talk there about this instead in github comments.
> > 
> > Forking would be great, ye and thanks.
> 
> give me your discord @

butterfly3ffect_0118

**Comment by deveers** [comment]
I'm sorry it does in fact, work

I had lots of mods so I clean reinstalled the game, repeated all the steps and it works!

**Comment by juhannnnnn** [comment]
> @peter1599 check the wiki, I made it! https://github.com/Nukem9/dlssg-to-fsr3/wiki/Dying-Light-2

i have done all those steps. i have dlss frame gen option now but it crashes every time i turn it on.

**Comment by ImASadBoy** [comment]
> > @peter1599 check the wiki, I made it! https://github.com/Nukem9/dlssg-to-fsr3/wiki/Dying-Light-2
> 
> i have done all those steps. i have dlss frame gen option now but it crashes every time i turn it on.

Follow the video tutorial, maybe you missed something, bottom page on that wiki link

**Comment by deejay1204** [comment]
> > > @peter1599 check the wiki, I made it! https://github.com/Nukem9/dlssg-to-fsr3/wiki/Dying-Light-2
> > 
> > 
> > i have done all those steps. i have dlss frame gen option now but it crashes every time i turn it on.
> 
> Follow the video tutorial, maybe you missed something, bottom page on that wiki link

Game keeps crashing for me as well with Frame Generation on . Epic games version of dying light 2 .

**Comment by ImASadBoy** [comment]
> > > > @peter1599 check the wiki, I made it! https://github.com/Nukem9/dlssg-to-fsr3/wiki/Dying-Light-2
> > > 
> > > 
> > > i have done all those steps. i have dlss frame gen option now but it crashes every time i turn it on.
> > 
> > 
> > Follow the video tutorial, maybe you missed something, bottom page on that wiki link
> 
> Game keeps crashing for me as well with Frame Generation on . Epic games version of dying light 2 .

What GPU and settings are you using? Can you send a pastebin link with the content of dlsstweaks.ini?

**Comment by peter1599** [comment]
> > > > @peter1599 check the wiki, I made it! https://github.com/Nukem9/dlssg-to-fsr3/wiki/Dying-Light-2
> > > 
> > > 
> > > i have done all those steps. i have dlss frame gen option now but it crashes every time i turn it on.
> > 
> > 
> > Follow the video tutorial, maybe you missed something, bottom page on that wiki link
> 
> Game keeps crashing for me as well with Frame Generation on . Epic games version of dying light 2 .

You have to delete epic game overlay i think:

How to disable the Epic Games Store overlay
Games bought from the Epic Store have a high chance of randomly crashing when the overlay is enabled.
To disable it, follow these steps:
1. Go into your Epic Games Store installation folder (usually C:/Program Files (x86)/Epic Games/Launcher)
2. Navigate to Portal/Extras/Overlay
3. Rename EOSOverlayRenderer-Win32-Shipping.exe and EOSOverlayRenderer-Win64-Shipping.exe to something else, like disabled-EOSOverlayRenderer.exe

**Comment by ImASadBoy** [comment]
> > > > > @peter1599 check the wiki, I made it! https://github.com/Nukem9/dlssg-to-fsr3/wiki/Dying-Light-2
> > > > 
> > > > 
> > > > i have done all those steps. i have dlss frame gen option now but it crashes every time i turn it on.
> > > 
> > > 
> > > Follow the video tutorial, maybe you missed something, bottom page on that wiki link
> > 
> > 
> > Game keeps crashing for me as well with Frame Generation on . Epic games version of dying light 2 .
> 
> You have to disable epic game overlay i think:
> 
> How to disable the Epic Games Store overlay Games bought from the Epic Store have a high chance of randomly crashing when the overlay is enabled. To disable it, follow these steps:
> 
> 1. Go into your Epic Games Store installation folder (usually C:/Program Files (x86)/Epic Games/Launcher)
> 2. Navigate to Portal/Extras/Overlay
> 3. Rename EOSOverlayRenderer-Win32-Shipping.exe and EOSOverlayRenderer-Win64-Shipping.exe to something else, like disabled-EOSOverlayRenderer.exe

It works fine with epic overlay for me, but try anyway!

**Comment by ttkrise** [comment]
The game crashes for me too with Frame Generation enabled.  Dying Light 2 Epic Games Version

**Comment by ImASadBoy** [comment]
> The game crashes for me too with Frame Generation enabled. Dying Light 2 Epic Games Version epic overlay off

What GPU and settings are you using? Can you send a pastebin link with the content of dlsstweaks.ini?

**Comment by ttkrise** [comment]
3060 TI settings medium https://pastebin.com/0Ahx9LiA

**Comment by ImASadBoy** [comment]
> 3060 TI settings medium https://pastebin.com/0Ahx9LiA

You need to remove the `;` on line 76, it should end up like this:

**Comment by ttkrise** [comment]
thank you that was the problem

**Comment by deejay1204** [comment]
> > > > > @peter1599 check the wiki, I made it! https://github.com/Nukem9/dlssg-to-fsr3/wiki/Dying-Light-2
> > > > 
> > > > 
> > > > i have done all those steps. i have dlss frame gen option now but it crashes every time i turn it on.
> > > 
> > > 
> > > Follow the video tutorial, maybe you missed something, bottom page on that wiki link
> > 
> > 
> > Game keeps crashing for me as well with Frame Generation on . Epic games version of dying light 2 .
> 
> What GPU and settings are you using? Can you send a pastebin link with the content of dlsstweaks.ini?

https://pastebin.com/NPrG6VRz
Used High Preset with DLSS Quality Setting . Game works without frame generation enabled . Ryzen 3700x + RTX 2070 Super . Even Alan Wake II works fine with the mod installed .

**Comment by juhannnnnn** [comment]
> > > @peter1599 check the wiki, I made it! https://github.com/Nukem9/dlssg-to-fsr3/wiki/Dying-Light-2
> > 
> > 
> > i have done all those steps. i have dlss frame gen option now but it crashes every time i turn it on.
> 
> Follow the video tutorial, maybe you missed something, bottom page on that wiki li

**Comment by juhannnnnn** [comment]
> > > @peter1599 check the wiki, I made it! https://github.com/Nukem9/dlssg-to-fsr3/wiki/Dying-Light-2
> > 
> > 
> > i have done all those steps. i have dlss frame gen option now but it crashes every time i turn it on.
> 
> Follow the video tutorial, maybe you missed something, bottom page on that wiki link

i made an error in specifying the file path in dlsstweaks.ini file. it dooesnt crash anymore but the generated frames dont feel that much smooth at all although the nvidia fps display shows that fps has increased.
