### ISSUE TITLE
[CRASH] Alan Wake II - DLSSTweaks

### ISSUE THREAD

**Issue by ShyVortex** [Nukem9/dlssg-to-fsr3#28]
When using the mod combined with DLSSTweaks, the game crashes as soon as Frame Generation is enabled from the menu.

Info about my PC specs:
[DxDiag.txt](https://github.com/Nukem9/dlssg-to-fsr3/files/13705231/DxDiag.txt)

![Screenshot 2023-12-18 152821](https://github.com/Nukem9/dlssg-to-fsr3/assets/111277410/e837be83-cd9f-44cc-aba3-ed80c6b949e3)
![immagine](https://github.com/Nukem9/dlssg-to-fsr3/assets/111277410/6e94692e-58c2-4261-a031-f96b79731261)

**Comment by Igihara** [comment]
Use the other one

**Comment by ShyVortex** [comment]
@Igihara 
when using the other one it says the mod is loaded upon launch but the option to enable FG is grayed out

**Comment by Nooblet16** [comment]
@ShyVortex I'd guess the reason your game crashed is the same reason why the other one doesn't work i.e. dbghelp.dll file doesn't exist in the directory so it isn't actually replacing DLSSG properly.

**Comment by Jackich2** [comment]
Also crashes the game, doesn't work

**Comment by ShyVortex** [comment]
@Nooblet16 I've tested the mod in A Plague Tale: Requiem which also lacks that DLL file, however it works fine there. I think the issue lies elsewhere

**Comment by Nooblet16** [comment]
@ShyVortex For that game where did you put the files? Just the same place as game.exe?

**Comment by ShyVortex** [comment]
@Nooblet16 yes

**Comment by nanowell** [comment]
Same, I hope it gets fixed.

**Comment by WikDra** [comment]
How about new version?

**Comment by ShyVortex** [comment]
@WikDra Just tested, unfortunately it doesn't work yet.

**Comment by ShyVortex** [comment]
Fixed with version 0.50, Frame Generation can now be toggled ON correctly even though it exhibits some ghosting artifacts while moving.
![immagine](https://github.com/Nukem9/dlssg-to-fsr3/assets/111277410/51ede5a8-a51e-4650-8142-c45ad020e7b7)
