### ISSUE TITLE
Duplicated frames?

### ISSUE THREAD

**Issue by peter1599** [Nukem9/dlssg-to-fsr3#280]
@Nukem9 Sorry for ping, but is this supposed happen?
I know its a strange question.

You can see that some frames stay longer because they are identical.

If you turn on DLSSG at 30 FPS it becomes smoother not "choppyer"

Video recorded at 30 FPS and my orignal FPS without fsr 3 frame gen is around 30 FPS

https://github.com/Nukem9/dlssg-to-fsr3/assets/25458870/0321e7c6-4dd7-48d2-9b72-83d4bc059c22

When I turn on frame gen with FSR 3 mod the movement becomes choppy instead of smoother. (Dying Light 2)
Same happens in Starfield.

This video I took shows multiple duplicated frames even while moving.

**Comment by Dravic** [comment]
How did you even manage to enable DLSS3 (FSR3) in Dying Light 2, exactly? That game is not compatible as far as I know, won't let you turn on Frame Generation with the mod installed.

Or do you have an RTX40 card?

**Comment by Nukem9** [comment]
There should be a log file called `dlssg_to_fsr3.log` in the game directory next to the DLL. Can you post it after running both Starfield and Dying Light?

**Comment by peter1599** [comment]
This is Dying Light 2:
[dlssg_to_fsr3.log](https://github.com/Nukem9/dlssg-to-fsr3/files/13793283/dlssg_to_fsr3.log)

This is Starfield:
[dlssg_to_fsr3.log](https://github.com/Nukem9/dlssg-to-fsr3/files/13793286/dlssg_to_fsr3.log)

**Comment by juhannnnnn** [comment]
> There should be a log file called `dlssg_to_fsr3.log` in the game directory next to the DLL. Can you post it after running both Starfield and Dying Light?

i have followed ur steps and managed to unlock frame generation. but the thing is the generated frames dont feel that much smooth at all despite the nvidia overlay showing that fps has doubled.

**Comment by peter1599** [comment]
And I think all games does this. This choppy thing.

**Comment by Nitro2137** [comment]
I have the exact same issue with your mod @Nukem9 in Cyberpunk. Tl;dr it Works 100% fine in SDR, but double stuttery frames (with motion artifacts) in HDR. Logs suggest everything’s fine, while it’s not. Great mod so far 🤍
