### ISSUE TITLE
lots of artifacts and glitches with subtitles and fast scenes

### ISSUE THREAD

**Issue by Cirrus135** [Nukem9/dlssg-to-fsr3#285]
I'm pretty sure you know about it, but I think it's actually the biggest problem with modification right now. I'm playing Jedi Survivor at the moment, and gameplay itself is extremely smooth and pleasant, what I unfortunately cannot say about cutscenes (especially these fast ones), in which lots of glitches and artifacts occur. Furthermore the artifacts affect on subtitles as well, which I was forced to disable (correct me if I'm wrong, but didn't it happen in older versionof FSR3 with official implementation 🤔 ? Im' not sure if you can do anything about it, cause I'm aware that modification in opposite of official implementation doesn't include motion vectors of particular game. But as I've written  at the beginning, I consider it as the biggest issue at the moment. Anyway thank you with all my heart for your work and life-rescuing mod. Have a good time with New Year!

**Comment by jojodunet** [comment]
Have you tried this? https://github.com/Nukem9/dlssg-to-fsr3/wiki/STAR-WARS-Jedi:-Survivor

**Comment by Cirrus135** [comment]
Broo, TY so much, now it works perfectly! Wouldn't have thought it's connected with letterbox. You think it applies to every game?

**Comment by jojodunet** [comment]
> Broo, TY so much, now it works perfectly! Wouldn't have thought it's connected with letterbox. You think it applies to every game?

It's a specific issue with Jedi Survivor. 
Just check the wiki for each game; the recommended approach is shared for each game https://github.com/Nukem9/dlssg-to-fsr3/wiki/Game-Compatibility-List

**Comment by Cirrus135** [comment]
Ok, now it makes sense. Thank you for help
