### ISSUE TITLE
How to make it work with AC Mirage

### ISSUE THREAD

**Issue by Curiosity007** [Nukem9/dlssg-to-fsr3#286]
I downloaded Luke's FG Mod, then put this, but it is crashing while game is starting

**Comment by jojodunet** [comment]
> I downloaded Luke's FG Mod, then put this, but it is crashing while game is starting

Hi, here it is not Luke's FG Mod repository. You could ask this in Luke's paid Discord channel😉

As for Nukem9's mod, AC Mirace currently does not support Frame Generation, so his mod is not compatible at this time.
