### ISSUE TITLE
Jedi Survivor EA Play Pro version

### ISSUE THREAD

**Issue by JesalR** [Nukem9/dlssg-to-fsr3#297]
I've tried a few different ways of getting SWJS working with the latest mod but can't seem to do it.

Tried DLSSTweaks and the standard install, but once I add the DLLs to `C:\Program Files\EA Games\Jedi Survivor\SwGame\Binaries\Win64`, the game no longer launches. Renaming to dxgi.dll causes an error that says there's something wrong with the game setup and to reinstall. It goes away if I delete the DLLs

Is it just not something that'll work with the EA Play Pro version of the game?

**Comment by Vladzor87do** [comment]
Try difitent Versions and turnoff overlay

**Comment by JesalR** [comment]
When you say different versions, do you mean of the mod?

Also, unsure which overlay you're referring to?

**Comment by Kenjy62** [comment]
Only v0.60 work with Jedi Survivor

**Comment by JesalR** [comment]
Amazing, thank you. 

Works perfectly bar some artifacts and ghosting in cutscenes
