### ISSUE TITLE
Cyberpunk 2077 - Enabling Frame Generation disables/hides HDR10 scRGB option in Video Settings

### ISSUE THREAD

**Issue by kaymanov-emitter** [Nukem9/dlssg-to-fsr3#299]
Pretty much what it says in the title.

When Frame Generation is enabled, HDR10 scRGB is no longer visible as one of the two HDR Options in Video settings. Only HRD10 PQ is selectable.

HDR10 scRGB is preferred over PQ, so this is a problem. **I don't know if this is a limitation of Frame Gen, or a bug with this mod.**

This happens when using either DLSS and FSR 2.1.

I'm using only the **nvgx.dll** method, **no DLSSTweaks**.

System:

OS - Windows 11
GPU - Nvidia RTX 3080
CPU - AMD 5800X3D
Motherboard - Asus B550

**Comment by jojodunet** [comment]
The issue isn't related to the mod.

Here's a potential explanation: https://steamcommunity.com/app/1091500/discussions/7/3875967397716382213/?l

**Comment by kaymanov-emitter** [comment]
> The issue doesn't seem to be related to the mod.
> 
> Here's a potential explanation: https://steamcommunity.com/app/1091500/discussions/7/3875967397716382213/?l

Drat, it seems you are right.

I'll close this issue.
