### ISSUE TITLE
Not support HDR, If you open the HDR in Cyberpunk 2077 game option will crash

### ISSUE THREAD

**Issue by tkp206093** [Nukem9/dlssg-to-fsr3#30]
![image](https://github.com/Nukem9/dlssg-to-fsr3/assets/29872453/2f938319-93db-43ab-bb04-b11e4defe902)

I test off the HDR in Cyberpunk 2077 game option FSR3 is OK
but if I turn on the HDR in game option, the game will crash

**Comment by Jackich2** [comment]
HDR no support now for mod

**Comment by alistair3149** [comment]
Duplicate of #14

**Comment by TheWoodsy** [comment]
Win11, 3090, CP2077
HDR works with 0.50

**Comment by tkp206093** [comment]
> Win11, 3090, CP2077 HDR works with 0.50

I test 0.5 HDR is work, not crash again.
