### ISSUE TITLE
not work for alan wake 2

### ISSUE THREAD

**Issue by Hydronerious** [Nukem9/dlssg-to-fsr3#303]
i did everything correctly but when launch .exe there is no message and FG greyed out as well.here is my log if that helps.
![屏幕截图 2024-01-02 171218](https://github.com/Nukem9/dlssg-to-fsr3/assets/155428756/796ccd98-5ec6-4d09-a331-06b22ed0fb7c)

**Comment by Vladzor87do** [comment]
Remove epicstore overlay

**Comment by ImASadBoy** [comment]
https://github.com/Nukem9/dlssg-to-fsr3/issues/223
https://github.com/Nukem9/dlssg-to-fsr3/issues/134

**Comment by Hydronerious** [comment]
that helps. appreciate it!
