### ISSUE TITLE
Returnal Game List Entry

### ISSUE THREAD

**Issue by IonSummability** [Nukem9/dlssg-to-fsr3#320]
[Returnal.pdf](https://github.com/Nukem9/dlssg-to-fsr3/files/13847560/Returnal.pdf)

**Comment by jojodunet** [comment]
I have added Returnal to the [Game Compatibility List](https://github.com/Nukem9/dlssg-to-fsr3/wiki/Game-Compatibility-List)

We need more feedback from other users.

**Comment by IonSummability** [comment]
There are quite a few here and also over at NexusMods confirming this specific problem, while there is nobody that ever reported it working. Sounds confirmed.

**Comment by jojodunet** [comment]
Is the .log file created where you stored the mod files?

If the .log file is not generated, it's either because the mod is not recognized or the mod files are not placed in the correct directory.

**Comment by IonSummability** [comment]
Yeah, it is placed in the correct directory where the exe is located and it is not creating any kind of log. If I rename nvngx.dll to dxgi.dll or 3d12.dll, the game crashes on startup. Returnal just ignores this mod in either version.

**Comment by jojodunet** [comment]
Do you have another game that works with the DLSSFG mod?

Could you try renaming nvngx.dll to version.dll, winhttp.dll, or dbghelp.dll?

**Comment by IonSummability** [comment]
It works with Jedi Survivor, Plague Tale, Cyberpunk, Alan Wake 2, Remnant 2 and Witcher 3 for me (so every game I own that also supports FG()

I renamed it to all your suggestions, still no FG Option where it should be in the Menu and also no log.
As I said, it does crash when renaming it to dxgi.dll or 3d12.dll, so it is injecting things.
The game just doesn't care about the FG Mod.

**Comment by jojodunet** [comment]
Wait for a new mod release; a fix could be implemented to make stubborn games, like Returnal, believe that they are running on an NVIDIA ADA Lovelace graphics card to unlock the FG option.

**Comment by jojodunet** [comment]
Wait for a new mod release; a fix could be implemented to make stubborn games, like Returnal, believe that they are running on an NVIDIA Ada Lovelace graphics card to unlock the FG option.

**Comment by IonSummability** [comment]
Game is working perfectly now, the difference in FPS with FSR3 is astounding.
HDR is fully suported and working on my LG CX.

**Comment by Hadrianneue** [comment]
> Game is working perfectly now, the difference in FPS with FSR3 is astounding. HDR is fully suported and working on my LG CX.

what did you do exactly to get it to work? i'm not even getting a log...

**Comment by IonSummability** [comment]
> > Game is working perfectly now, the difference in FPS with FSR3 is astounding. HDR is fully suported and working on my LG CX.
> 
> what did you do exactly to get it to work? i'm not even getting a log...

I simply added "version.dll" to the folder where the executable is located. For me that is "X:\SteamLibrary\steamapps\common\Returnal\Returnal\Binaries\Win64". From there, the options shows up in the graphics menu.
