### ISSUE TITLE
Mod not working for cyberpunk when using other mods

### ISSUE THREAD

**Issue by g5d8** [Nukem9/dlssg-to-fsr3#327]
I had this mod installed on my cyberpunk playthrough and it was working fine until I started installing some other cyberpunk mods. After that the mod wouldn’t work at all. I tried to uninstall all of my cyberpunk mods, and i reinstalled this too, but it still didn’t work. I haven’t found any solutions yet.

**Comment by SpookieWookie** [comment]
I've had similar weirdness with Cyberpunk and it was making mod testing a nightmare, rebooting usually made it work again but not ideal for checking mods back to back. Are you injecting the mod using nvngx.dll? Try renaming it to dxgi.dll - it started working fine without having to reboot after that for me.

**Comment by Dravic** [comment]
Try this:

Use the DLSSTweaks version and rename its nvngx.dll to dxgi.dll

**Comment by g5d8** [comment]
> Try this:
> 
> Use the DLSSTweaks version and rename its nvngx.dll to dxgi.dll

where do I get DLSSTweaks?

**Comment by Dravic** [comment]
> where do I get DLSSTweaks?

https://www.nexusmods.com/site/mods/550

**Comment by g5d8** [comment]
> > where do I get DLSSTweaks?
> 
> https://www.nexusmods.com/site/mods/550

i did all of those steps and renamed the DLSSTweaks nvngx.dll to dxgi.dll and the fsr3 mod still isn't working.

**Comment by Dravic** [comment]
> > > where do I get DLSSTweaks?
> > 
> > 
> > https://www.nexusmods.com/site/mods/550
> 
> i did all of those steps and renamed the DLSSTweaks nvngx.dll to dxgi.dll and the fsr3 mod still isn't work
> 
> edit - should've elaborated, I tried to install redscript after doing this, but the fsr3 mod still didn't work after installing.

Did you follow the README of Nukem9's DLSS3-to-FSR3 mod (DLSSTweaks edition) where Nukem9 tells you to edit the dlsstweaks.ini line below

>;  Other DLLs such as DLSS FrameGen (nvngx_dlssg) can also be overridden using this too:

**Comment by g5d8** [comment]
> > > > where do I get DLSSTweaks?
> > > 
> > > 
> > > https://www.nexusmods.com/site/mods/550
> > 
> > 
> > i did all of those steps and renamed the DLSSTweaks nvngx.dll to dxgi.dll and the fsr3 mod still isn't work
> > edit - should've elaborated, I tried to install redscript after doing this, but the fsr3 mod still didn't work after installing.
> 
> Did you follow the README of Nukem9's DLSS3-to-FSR3 mod (DLSSTweaks edition) where Nukem9 tells you to edit the dlsstweaks.ini line below
> 
> > ;  Other DLLs such as DLSS FrameGen (nvngx_dlssg) can also be overridden using this too:
> > nvngx_dlssg=[your game's path here]\dlssg_dlsstweaks_wrapper.dll
> 
> ?

it’s fixed, i didn’t see that line at first. thanks for the help!
