### ISSUE TITLE
Seems to be repeating frames instead of actually generating them (on a 2080 Super)

### ISSUE THREAD

**Issue by TheEnhas** [Nukem9/dlssg-to-fsr3#337]
I tested it in both Cyberpunk 2077 and Alan Wake 2, and while the frame generation option shows up just fine and the FPS counter is clearly higher, the games don't reflect that and look and feel like they're running at half refresh rate (so 30 FPS on a 60Hz monitor). I notice the difference as soon as I turn frame generation on... the supposed extra frames don't seem to actually be there.

What I don't get is that others (mostly on 30-series GPUs) don't have this issue, and frame generation works like it should. Are 20-series GPUs just too slow to do FG effectively or is there another problem?

**Comment by TheEnhas** [comment]
Yeah, but it should still at least _look_ like it's 60+ FPS. Instead, it seems to be visibly 30 FPS no matter what the FPS counter says, which defeats the whole point.

I don't understand why FG has never worked for me when I've seen videos where it's visibly smooth, though I do think all of those were on 30-series GPUs.

**Comment by Gaffer13** [comment]
It is visibly smooth for me on a 2060. But there are limits to this - 30 to 60 isn't the best case scenario for frame generation, even when done natively on the 4000 series. And when your cap is so low, you could be going from 60 real frames to 30 real frames with frame generation on top - which is going to look worse.

**Comment by Gaffer13** [comment]
And even on a high refresh rate monitor, FSR comes at a cost, so you're not getting twice as many frames. I was going from 45 real frames to 70 fps with frame generation (so 35 real frames) in Jusant. So it's smoother, but less responsive.

**Comment by TheEnhas** [comment]
From what I've read the 60+ FPS suggestion seems to also mean having that when FG is on but _before_ it takes effect... ie. you need a 120Hz monitor minimum so that 60 "real" FPS is used, not just being able to reach it.

The whole reason I've been trying FG is because I'd hoped to smooth out performance dips. I can already get 60 FPS on a 60Hz monitor in both Cyberpunk 2077 and Alan Wake 2 (albeit with lowered settings), but there's some problem areas in both games that tank FPS. I assumed that I could just turn on FG and the game would look and perform the same, but with no or lessened FPS drops due to FG kicking in, but that's not how it works at all. Instead, the game looks and feels like it's running at 30 FPS when FG is on.

So yes, FG seems to be pointless unless you have a high refresh monitor.

**Comment by Gaffer13** [comment]
Yes, the 60 fps suggestion means 60 to 120. In my experience, going a little lower is OK - and the improvement from 45-50 to 70-80 is more noticeable. While 60 real fps looks OK even without frame generation. 

But yes, 30fps is very low, with or without FG. While the problem areas won't necessarily improve - they could be RAM/VRAM bottlenecked, or optimization issues.

**Comment by TheEnhas** [comment]
I've fixed this issue by installing the recent beta of RTSS and the games I've tried (Alan Wake 2, Cyberpunk 2077 and Hogwarts Legacy) all look fairly smooth now with frame generation on a 60Hz monitor.

In-game vsync must be disabled + forced on via the NVCP, and RTSS **must** be set to a 60 FPS cap with "NVIDIA reflex" selected as the framerate limiter. With this it's almost as smooth looking as native 60 FPS and input lag isn't that bad either IMO. It does help with some dips but it doesn't help much with traversal stutter, or with stutter caused by ray-tracing enabled (at least in my case). But I'm able to run all three of those games on their highest non-RT presets now with minimal issues, which is great.

**Comment by Gaffer13** [comment]
Do you need to use RTSS at all? Nvidia's limiter works fine for me.

**Comment by Gaffer13** [comment]
FG itself is supposed to force Reflex. And you're not supposed to use in-game Vsync.

**Comment by TheEnhas** [comment]
I meant that I was using driver-level vsync (with in-game disabled), and FG definitely did not seem to force Reflex given all the lag and judder I had. I do know that driver level vsync + RTSS cap with the "NVIDIA reflex" limiter does indeed work, and this is the first time I've actually gotten FG to work as intended.
