### ISSUE TITLE
Hitman: WoA ReShade_Addon

### ISSUE THREAD

**Issue by ABDX80** [Nukem9/dlssg-to-fsr3#339]
![Hitman 3 Screenshot 2024 01 10 - 16 47 10 46](https://github.com/Nukem9/dlssg-to-fsr3/assets/152691067/cf02e408-9da0-4d40-b675-30e5668b725a)

Launching Hitman with ReSahde_Addon version with HDR10 Addon causes the game to launch in blue filter as seen in the snapshot above.

Do note that FG Mod works perfectly fine. Also, as soon I disable this HDR10 Addon Mod the blue filter goes away.
Hitman works absolutely flawless with ReShade overlay and any shaders with FG Mod, the problem only exist when I use any ReSahde_Addon such as HDR10.

Is it possible to fix this issue in an upcoming update or is there any workaround for it?
Please let me know!

@Nukem9 
Thanks!

**Comment by Nukem9** [comment]
I can't fix this unfortunately. The ReShade addon has to be patched.
