### ISSUE TITLE
Force FG ratio and Game Engine Rendering FPS

### ISSUE THREAD

**Issue by People-11** [Nukem9/dlssg-to-fsr3#348]
I use FG for a different purpose than others: I just want my frames to be smooth but not higher.

In other words, If a game can run ~90FPS on my PC, I won't use FG to make it achieve 140FPS or higher but fluctuating frame rates. Instead, I will limit 60FPS in game and use FG to achieve very stable 120FPS.

This works excellent on CyberPunk 2077, I limit to 60FPS via in-game settings and use FG mod to generate fixed 2x frames then enable VSync in NVIDIA Control Panel to get really smooth 120FPS experience.

However, this not working on Starfield, Starfield doesn't have something like in-game FPS limit setting. So I can only limit frames in NVIDIA Control Panel. When I limit to 60FPS, I can get 30FPS engine rendering and 60FPS generated. But when I limit to 120FPS, I will get ~90FPS fluctuating engine rendering and ~120FPS fluctuating generated.

This shows two problems: 
1. FSR doesn't use a fixed ratio by default, even though I get a steady 120FPS in 2077, that's just the maximum ratio it reaches. 
3. If there is no in-game FPS limitation and the Control Panel is used to limit it, it actually limits the overall output FPS, not the engine output FPS, and coupled with the first problem, It would be a waste of performance (it takes more performance for the game to render 30FPS more than FG 30FPS), we can't get a smooth frame generation time, and we can't get a no-shutter gameplay experience.

Solution:
Ideally, if FG is able to fix the FG ratio, the game engine should actively reduce the number of frames output to match the fixed FG in order to achieve a smooth frame output under the action of VSync.

P.S. Why don't I buy a monitor that supports VRR?
1. Seems this FG mod is not working very well with VRR
2. I also do screen recording, floating or mismatched frame rates make my videos judder
3. If I have the money to buy a monitor, I rather buy a stronger GPU.

**Comment by xv0t** [comment]
I don't think it's possible to do what you're asking, you may want to use Lossless Scaling, since it requires you to limit the game's framerate to a fixed value for it to work properly.

**Comment by cichy45** [comment]
The framegen requires some GPU performance, so if you have 90 FPS without FG, after enabling FG your real FPS might drop <60 FPS and you will not get stable 120 FPS then. It shout not drop so much (from 90 to <60) but who knows, maybe this is some edge case.

FrameGen will double FPS only if you have performance margin. 

Framegen always double FPS, but if you are on max gpu load, or almost max gpu load, and you have 70 before frame gen and 100 FPS after frame gen, it does not mean you have 70 real frames and 30 generated. 100 fps after enabling frame gen means your real fps dropped from 70 to 50 and 50 got doubled to 100.

You can only go from X fps to 2 * X FPS if you limit in game FPS to have much performance margin (4K requires more margin, lower resolution less). So for example if I limit CP2077 from 100 FPS at 100% GPU load, to 60 FPS at 60 % GPU load, then enable framegen I will have 120 frames at (for example) 90% gpu load.

I hope I explained it clearly.

**Comment by People-11** [comment]
@cichy45 
Thanks for your explaination, I understand what you are saying. But the main point I was going to make was: for the games doesn't have in-game fps limit, like Starfield, is there anything that FG Mod can do to limit the engine output, so FG can get enough performance to go 2x frame rate, instead of FG and engine robbing GPU performance, making FG not be able to achieve its best effect?

My actual run: I got 90-105FPS with 100% GPU in Cyberpunk 2077 (depending whether I'm in city area), and got only 60% GPU load when limit to 60FPS in-game. After using FSR3 Mod to 120FPS, my GPU load is 68-78%. Atst I use iGPU as my screen recorder encoder, which will not have massive extra load to dGPU. So doing 120FPS gaming and 120FPS recording is not a problem for me.

My opinion to VRR: Good thing but I still not want to use it. Just like HDR, even if they have harmonized hardware and certification standards, they still have a lot of unresolved issues with software.

**Comment by Nukem9** [comment]
Frame limiting and frame pacing are outside the scope of dlssg-to-fsr3. I simply replace Nvidia's interpolation algorithm with AMD's interpolation algorithm. Nothing more.

[Nvidia Streamline](https://github.com/NVIDIAGameWorks/Streamline) and to be more specific, `sl.dlss_g.dll`, ultimately control pacing and framerate limits. Reflex works similarly with help from the graphics driver (NvAPI). The driver handles VRR and VSync. These aren't open source so we can't look at the code.

[RTSS beta](https://www.youtube.com/watch?v=WiiYfjpN4EY) has support for framerate limiting via Reflex which might solve part of the GPU usage problem. I haven't tried it. Though from what I can tell it's no different than Nvidia Control Panel limits.

**Comment by People-11** [comment]
Thanks dev, doesn't look like there's a better solution until the game is adapted to FG, I will close this issue.
