### ISSUE TITLE
starfield crashing the moment i enable frame gen

### ISSUE THREAD

**Issue by rmills2914** [Nukem9/dlssg-to-fsr3#349]
i have the hardware accelerated gpu scheduling turned on and vsync off but i still cant get fsr 3 to work no matter what

**Comment by Vladzor87do** [comment]
https://github.com/Nukem9/dlssg-to-fsr3/wiki/Starfield

**Comment by jojodunet** [comment]
Is your game up-to-date, and are you aware of all the steps [here](https://github.com/Nukem9/dlssg-to-fsr3/wiki/Game-Compatibility-List) ?
Try both versions, 0.80 and 0.9, using the regular method (nvngx.dll) as DLSSFG has been reported to work for other users.

**Comment by rmills2914** [comment]
i have tried every version from .6 to .9 dlss tweaks and the regular method and nothing works and i make sure its in the right folder and followed all the directions on the readme files and the wiki

**Comment by jojodunet** [comment]
Could you please share the .log file using the regular method (nvngx.dll) of version 0.90?

**Comment by rmills2914** [comment]
[dlssg_to_fsr3.log](https://github.com/Nukem9/dlssg-to-fsr3/files/13925174/dlssg_to_fsr3.log)

**Comment by rmills2914** [comment]
this is all it shows

**Comment by rmills2914** [comment]
i got it to work i reinstalled the game and dropped the fsr 3 files back in and it worked somehow

**Comment by jojodunet** [comment]
Good, I believe you can close this issue.

**Comment by jojodunet** [comment]
Good.

I believe you can close this issue.
