### ISSUE TITLE
Building from source

### ISSUE THREAD

**Issue by HKunogi** [Nukem9/dlssg-to-fsr3#356]
Are there any specific steps on how to build it from source? Tried several things, using ninja and vcpkg, but i couldn't make it build properly, also seems theres no vs studio project on the files. Any info is welcome.

**Comment by nbrideau** [comment]
It is a cmake project so there are no solution files. Open VS,  File > Open > Folder... > Choose git dir. This will generate the cmake build system then choose what to build from the dropdown e.g. "Universal Debug x64"  then Build > Build All. Have to init git submodules and build the fidelity fx sdk as well.

**Comment by HKunogi** [comment]
Thanks, i always forget that nowadays vs studio supports cmake natively, and i dont need the cmake standalone app itself.

**Comment by lazerl0rd** [comment]
@nbrideau, were you able to successfully build? There seem to be quite a few undeclared identifiers and it @Nukem9 may be using a private fork of FidelityFX-SDK.

**Comment by Nukem9** [comment]
https://github.com/Nukem9/dlssg-to-fsr3/commit/b6c02911fc90226d3ffc2cf662ccb2ad8f18c209
