### ISSUE TITLE
Avatar frontiers of pandora 3080 ultra 4k?

### ISSUE THREAD

**Issue by TIGamingTV** [Nukem9/dlssg-to-fsr3#357]
Anyone tried this?

**Comment by MJ12MJ** [comment]
Avatar Frontiers of Pandora already support AMD FSR3 with RTX 3080.

**Comment by TIGamingTV** [comment]
> Avatar Frontiers of Pandora already support natively AMD FSR3 with RTX 3080.

Frame Gen too?

**Comment by MJ12MJ** [comment]
FSR3 include frame gen too.
