### ISSUE TITLE
Remnant II version 402,459

### ISSUE THREAD

**Issue by MossBorne** [Nukem9/dlssg-to-fsr3#378]
Versions .80 and .90 no longer working. 
With v.80 the DLSS3 FG option is available, however, option can not be turned on. 
(With v.80, DisableNvidiaSignatureChecks was used, Hardware Acceleration is enabled)
May need to be fixed next update.

**Comment by artur-graniszewski** [comment]
https://www.nexusmods.com/site/mods/757?tab=videos - there's a video showing the gameplay from Remnant2 with Nukem9 mod. Try to test the DLSS Enabler mod.

**Comment by MossBorne** [comment]
Yes, was able to get this resolved. I deleted the mod files and verified the game files, reapplied the mod files ( 80) and all is working now.
