### ISSUE TITLE
It doesn't seem to work in Alan Wake 2(version 1.0.16)

### ISSUE THREAD

**Issue by Darks41** [Nukem9/dlssg-to-fsr3#391]
I tried many installation methods(Version, Tweaks, etc)，but the FG option is still grayed out.
It work fine in other games: Hogwarts, Whicher3.

**Comment by StepAsR** [comment]
It works for me. Easy with the universal version.
RTX 3060 and Frame generation is working flawlessy.

**Comment by Darks41** [comment]
It works, I reinstall the game and MOD(universal version), thanks.
