### ISSUE TITLE
Frame Gen Mod by Nukem

### ISSUE THREAD

**Issue by russkay03** [Nukem9/dlssg-to-fsr3#402]
Want to use Frame Gen file dlssg-to-fsr3-0.90-738-0-90 for MSFS 2020. 
The mod has been moved to Nexus mods and unless a Premium member - which is a yearly subscription, cannot download the file as it is more than 3MB's.
Is there any other location or way to download the file?

**Comment by LeBlackMeow** [comment]
TF are you saying ? You don't need premium to download from Nexus. 
![0r0JkLp](https://github.com/Nukem9/dlssg-to-fsr3/assets/160722394/e098bd22-ef9d-4327-962d-c1aa8c927bd5)

**Comment by LeBlackMeow** [comment]
> I have been trying that for two days with no success. Above that box, it says, Free downloads for or only files up to 3MB's. This file is 4.4 MB's and just won't download, can't even click on it. Any suggestions?

I've uploaded all three files from nexus. Hope it helps you: [https://pixeldrain.com/u/9h8R4LfD](https://pixeldrain.com/u/9h8R4LfD)

**Comment by russkay03** [comment]
Thank you very much for the three files from Nexus, apologies for the delay in responding but have just downloaded and installed them. I have a Nvidia GeForce RTX 2070 Super and resolution of 1920X1080. On first start up, Iam getting a significant increase in FPS.
Thanks again for your help.
