### ISSUE TITLE
Mod seems bugged with GSYNC/VSYNC?

### ISSUE THREAD

**Issue by Kirsutan** [Nukem9/dlssg-to-fsr3#420]
The mod used to work just fine a few weeks ago (CP2077, DL2, Darktide) (3060ti, 5800X3D, 32GB of RAM, VSYNC forced globally, everything configured correctly).

Recently though, it works and doesn't. Framerate goes up, but the game doesn't feel smooth. Somehow GSYNC/VSYNC is bugged, and the result is a juddery mess. 80fps natively feels a TON smoother than 120+ FPS with the mod. Feels like GSYNC is syncing to the original FPS and frames are being inserted on top of that, if it makes sense.

Happens in all games, I have also tried to rollback drivers to 537 with no help, also different DLSS versions ranging from 3.1.11 to 3.7.0. The issue is there regardless if I use NVNGX version or any of the universal ones. Is the mod broken, or is the issue on my end?

**Comment by TimmyP777** [comment]
Your end.

Is it CP2077? Is HDR color saturation slider at 0?

**Comment by TimmyP777** [comment]
Deerrrrrr buncha idiots here. The problem is on your end.

**Comment by Kirsutan** [comment]
> Your end.
> 
> Is it CP2077? Is HDR color saturation slider at 0?

Yes, I tried all troubleshooting steps for CP2077. No clue what the cause was. For Darktide, turning of all lens flare settings fixed the issue, something with a new game update changing the way FG works under UI and other HUD elements. 

Also, I got a 4070ti Super, NV framegen works just fine in CP2077 so whatever lmao.
