### ISSUE TITLE
Interpolation 

### ISSUE THREAD

**Issue by ohboy30** [Nukem9/dlssg-to-fsr3#421]
Can you fix the hud in msfs2020? It makes the game unplayable.

**Comment by Sousaboi** [comment]
Unfortunately the developer was “sabotaged” by NVIDEA themselves for I believe exposing them that Frame Generation is possible for pretty much all RTX series cards, and not just the 40 series. As of right now, this mod has been “discontinued”, as the last update was back in January. It sucks I know, I play MSFS too. I’m currently trying to figure out a way to fix it myself!

**Comment by Sousaboi** [comment]
Actually I just read somewhere that the mod isn’t finished, but the dev plans on returning back to it sometime in the future. Don’t know when that would be..

**Comment by ohboy30** [comment]
Big companies suck! Thanks for letting me know

**Comment by ohboy30** [comment]
Big companies suck! Thanks for letting me know

**Comment by Sousaboi** [comment]
😃👍
