### ISSUE TITLE
[Diablo IV] Dlssg-to-fsr3 Loading but FG Option Greyed Out

### ISSUE THREAD

**Issue by lazerl0rd** [Nukem9/dlssg-to-fsr3#424]
I'm using the `version.dll` Universal DLLs with Diablo IV. `dlssg_to_fsr3.log` (see below) is created but the FG option is still greyed out in-game. `FenrisDebug.txt` doesn't complain about DLSS FG not being supported (without `dlssg-to-fsr3`, a line in the log said that).  Hardware-Assisted GPU Scheduling is enabled in Windows. The only references to DLSS are now:

```log
W 2024.05.22 12:26:32.303280 0	[Game] [13-26-32][streamline][warn][tid:22988][6s:124ms:620us]ota.cpp:439[getOTAPluginForFeature] No updated version found for plugin: dlss_0
W 2024.05.22 12:26:32.303303 0	[Game] [13-26-32][streamline][warn][tid:22988][6s:124ms:643us]ota.cpp:439[getOTAPluginForFeature] No updated version found for plugin: dlss_g_0
...
I 2024.05.22 12:26:37.840945 0	[Game] Video_Card NVIDIA GeForce RTX 3060 Laptop GPU (0x10de|0x2520)
I 2024.05.22 12:26:37.849492 0	[Game] [Prism] DLSS is enabled
```

Attachements:

[dlssg_to_fsr3.log](https://github.com/Nukem9/dlssg-to-fsr3/files/15403290/dlssg_to_fsr3.log)

![image](https://github.com/Nukem9/dlssg-to-fsr3/assets/24303423/f2a6fed5-ac3c-420b-9e5f-919b84dd1882)

**Comment by lazerl0rd** [comment]
Tried building `main` (to test https://github.com/Nukem9/dlssg-to-fsr3/commit/89ddc8c1cce4593fb420e633a06605c3c4b9c3cf) however hit into a few issues mentioned at https://github.com/Nukem9/dlssg-to-fsr3/issues/356#issuecomment-2124922042.

**Comment by LeBlackMeow** [comment]
https://us.forums.blizzard.com/en/d4/t/cant-activate-frame-generation-anymore/161422

**Comment by lazerl0rd** [comment]
@LeBlackMeow, thanks for bringing that up. Looks like I'll give it a spin tomorrow as DLSS FG should reportedly be back in the upcoming patch.

**Comment by lazerl0rd** [comment]
According to https://news.blizzard.com/en-us/diablo4/23964909/diablo-iv-patch-notes, DLSS should be restored but I'm still unable to select it.

**Comment by lazerl0rd** [comment]
Also tried LukeFZ's Uniscaler simulating RTX 4000 Series and NVAPI results which also didn't let me select the option.

**Comment by lazerl0rd** [comment]
It's disabled server-side again - https://www.reddit.com/r/diablo4/comments/1d3bo6t/comment/l66g50t.

**Comment by Maxcension** [comment]
Works perfectly now!

**Comment by lazerl0rd** [comment]
I'm noticing aconsistent stutter with FG, but it does indeed seem to work! Closing the issue.
