### ISSUE TITLE
Ignore all my previous Issues, Nukem

### ISSUE THREAD

**Issue by Sousaboi** [Nukem9/dlssg-to-fsr3#429]
Ill say one thing, this mod has done great, but Ive moved on to the lossless scaling, as the interpolation doesnt happen, BUT i have to pay the price of only 50 fps average vs the 100+ fps average. Until the interpolation issue gets resolved, I will be using the lossless scaling. Would LOVE a reply! 

Also, would you be interested in the idea of partnering up with another coder that can help you? Its been 6 months and the interpolation is still a massive problem for MSFS2020. Thinking maybe a second coder could try to help!

**Comment by TimmyP777** [comment]
lol get lost then? This isn't a forum about video encoding. Noobs like you have zero business here.

PS: This is frame GENERATION, if it was interpolation FPS would be doubled, exactly.

Why not learn what you are doing? What you are talking about? Educate yourself a little?

Funny because lossless scaling IS EXACTLY interpolation, and nothing more.

**Comment by Sousaboi** [comment]
Noobs like me have every right to be here. If you don’t want them, go do Patreon or something. Noobs like me also like stuff to be free, and I’m not willing to pay for a broken mod. It’s okay though, Lossless Scaling on Steam performs way way better than this Piece of Sh*t mod! Closing this for YOUR pleasure, have a good one 😉

**Comment by TimmyP777** [comment]
lol look at you. What did I just say?

"Broken mod" ...nope.

Lossless scaling is video encoding. It is not frame generation. You are watching an encoded video in real time, there is not much else that can be done do it.

If you think it even compares to this actual frame generation mod? Then you are using THIS wrong. It is on YOU.

Like I said, educate yourself. Then you wont look like such a fool.

**Comment by Sousaboi** [comment]
> lol get lost then? This isn't a forum about video encoding. Noobs like you have zero business here.
> 
> PS: This is frame GENERATION, if it was interpolation FPS would be doubled, exactly.
> 
> Why not learn what you are doing? What you are talking about? Educate yourself a little?
> 
> Funny because lossless scaling IS EXACTLY interpolation, and nothing more.

The issue is in fact interpolation 

> lol look at you. What did I just say?
> 
> "Broken mod" ...nope.
> 
> Lossless scaling is video encoding. It is not frame generation. You are watching an encoded video in real time, there is not much else that can be done do it.
> 
> If you think it even compares to this actual frame generation mod? Then you are using THIS wrong. It is on YOU.
> 
> Like I said, educate yourself. Then you wont look like such a fool.

Got nothing better to do huh? Sure I’m a dumbass, I’ll admit that, I have no idea how this shit works. 🤣 I at least know what works for me. Now go on and pick on someone else, ‘cause you did a hell of a job doing it to me 😂
