### ISSUE TITLE
Portal Prelude RTX Testing

### ISSUE THREAD

**Issue by Z4ndyz** [Nukem9/dlssg-to-fsr3#44]
Hello,
I've managed to load up Frame Generation(or well at least the toggle) into Portal Prelude RTX (Streamline game that uses DXVK) using the dlsstweaks method, i guess any streamline game will support this kind of injection?

Considering it uses DXVK but VK isn't fully supported can somebody with more expertise try this game out too?

With framegen off in a room i was having 55fps but with it on i was jumping to 90-100 (and ingame console doesn't reflect this fps growth)

I suspect the frames aren't exactly interpolated but in some sort they're being duplicated but they're behind 1fps, it feels stuttery and moving objects at high speed leave a ghosting trail of their silhouette compared to cp2077 and tw3

I was just wondering if vk support is completely absent for now from fsr3.0(not officialy supported yet) or something else is at fault and catch the errors that are being thrown

This was an interesting experience i was surprised it even booted and not straight up crash  (rtx 3070 150w laptop)

**Comment by remileduc** [comment]
Hello,

I tested it in Portal RTX, but I can try in Prelude RTX tomorrow.

I have mixed results with RTX3080:
- If I update the DLSS DLLs with latest (3.5.10), the game doesn't start with dlss-to-fsr3
- If I keep the game's version of DLSS (2.5), then I can play with dlss-to-fsr3 (I get the popup)
  - without FSR3, I have 57-60 FPS
  - with FSR3 I have around 50-55 FPS, so LESS than without

I don't use dlsstweaks though. I simply put the DLL files in the `bin/.trex` folder. I get the FSR3 popup so it is loaded correctly.

**Comment by Onlineman19** [comment]
> Hello, I've managed to load up Frame Generation(or well at least the toggle) into Portal Prelude RTX (Streamline game that uses DXVK) using the dlsstweaks method, i guess any streamline game will support this kind of injection?
> 
> Considering it uses DXVK but VK isn't fully supported can somebody with more expertise try this game out too?
> 
> With framegen off in a room i was having 55fps but with it on i was jumping to 90-100 (and ingame console doesn't reflect this fps growth)
> 
> I suspect the frames aren't exactly interpolated but in some sort they're being duplicated but they're behind 1fps, it feels stuttery and moving objects at high speed leave a ghosting trail of their silhouette compared to cp2077 and tw3
> 
> I was just wondering if vk support is completely absent for now from fsr3.0(not officialy supported yet) or something else is at fault and catch the errors that are being thrown
> 
> This was an interesting experience i was surprised it even booted and not straight up crash (rtx 3070 150w laptop)

Hey dude, could you please describe how you exactly you got FG to work with Portal RTX?

**Comment by Z4ndyz** [comment]
Used the DLSS_Tweaks method of 0.31 but try with 0.5 or 0.6
Read the DLSS Tweaks readme and dlss_tweaks_version of dlssg-fg-fsr 
Folder should be .trex btw for portal
You'll get the toggle but you'll get exactly duplicated frames not interpolated + ghosting since VK is not yet supported but i'm not sure if it's just buggy or straight up not supported but the toggle for dlss-fg will work

**Comment by remileduc** [comment]
Nope, can't make it work... The good thing with 0.6 is that I can now launch the games with the updated DLSS dlls to 3.5.10, but I don't have the frame generation option in game, with either methods (vanilla or with tweaks), in either games.
Thus the bad performance in my first message (FG is just not detected / enabled).

I'd be interested to see how you make it work @Z4ndyz 

<details>
<summary>Screenshots that shows that *dlssg-to-fsr3* is correctly configured, but no option in game</summary>
![image](https://github.com/Nukem9/dlssg-to-fsr3/assets/2204024/5c7af872-46a4-4a5c-b2df-8537415fd03c)
![image](https://github.com/Nukem9/dlssg-to-fsr3/assets/2204024/8b1731e6-efe2-4b11-9f99-e43d5bb96cd1)
![image](https://github.com/Nukem9/dlssg-to-fsr3/assets/2204024/867f246e-d94b-48fc-a446-4ccd1311f9e4)
![image](https://github.com/Nukem9/dlssg-to-fsr3/assets/2204024/49d17d43-cbae-4276-8d86-fce024596eb6)
</details>

**Comment by Z4ndyz** [comment]
Closing this issue since it's been adressed in #141
