### ISSUE TITLE
Frame Generation Not Working in Throne & Liberty

### ISSUE THREAD

**Issue by ProgrammingDump** [Nukem9/dlssg-to-fsr3#464]
If anyone knows how to make it work in Throne and Liberty, I'd be thankful.

**Comment by xCaptainTroy** [comment]
you cant, there is easy anti cheat

**Comment by Heaphobia** [comment]
hi every one, to use Frame Generation need have GPU 40 series, but my wife bought 4060ti MSI SLIM 16GB when frame generation on u can randomly get crush and error about "out of video memory"

**Comment by Heaphobia** [comment]
hi every one, to use Frame Generation need have GPU 40 series, but my wife bought 4060ti MSI SLIM 16GB when frame generation on u can randomly get crush and error about "out of video memory"

**Comment by xCaptainTroy** [comment]
> hi every one, to use Frame Generation need have GPU 40 series, but my wife bought 4060ti MSI SLIM 16GB when frame generation on u can randomly get crush and error about "out of video memory"

manually tweak virtual memory and set it to 16 GB
