### ISSUE TITLE
Debug screens appear issue

### ISSUE THREAD

**Issue by DanielZockt247** [Nukem9/dlssg-to-fsr3#48]
Whenever I enable Frame Generation in Cyberpunk 2077, 6 additional "Debug" screens appear. How can I disable them?

![image](https://github.com/Nukem9/dlssg-to-fsr3/assets/100319897/05e14ade-cc9e-4226-923d-3e002ca3f2a9)

**Comment by TheOriginalBabu** [comment]
Also in MSFS

**Comment by tkp206093** [comment]
BUG in 0.4
FIX IN 0.41

**Comment by CasualDev242** [comment]
Yep, current release is in debug mode. Whoopsy.
