### ISSUE TITLE
0.41 doesn`t work in Cyberpunk 2077

### ISSUE THREAD

**Issue by NOHEATED** [Nukem9/dlssg-to-fsr3#49]
There is no such file as nvngx.dll in that game by default

**Comment by TheOriginalBabu** [comment]
pls close this issue

**Comment by NOHEATED** [comment]
> pls close this issue

Why?

**Comment by TheOriginalBabu** [comment]
read readme

**Comment by NOHEATED** [comment]
> read readme

Ok

**Comment by NOHEATED** [comment]
> read readme

Ok, it was my bad cause I didn`t know how to merge and what`s the difference to just clicking on it, mb

**Comment by NOHEATED** [comment]
Ok, it was my bad cause I didnt know how to merge and whats the difference to just clicking on it, mb
