### ISSUE TITLE
Cyberpunk 2077 split into 7 different render windows on the 0.40

### ISSUE THREAD

**Issue by Onlineman19** [Nukem9/dlssg-to-fsr3#50]
Followed all of the instructions correctly, but this still happens. Doesn't happen when you pause or open the main menu.

![Cyberpunk2077_tji1pSIx9b](https://github.com/Nukem9/dlssg-to-fsr3/assets/79145410/38b1f425-a151-404a-ba6c-f9cd60eb8c6e)

**Comment by Igihara** [comment]
Use 0.41..

**Comment by Onlineman19** [comment]
> Use 0.41..

Bruh moment
