### ISSUE TITLE
(Cyberpunk 2077) Playing with RivaTunerStatisticsServer seems to introduce extreme input lag

### ISSUE THREAD

**Issue by Onlineman19** [Nukem9/dlssg-to-fsr3#51]
Title. The input lag seems to decrease when lowering the fps limit, but there still is a little of it. Really, any way to limit FPS seems to introduce input lag. Disabling RTSS seems to fix this. Possibly VSync also does that.

Also, question, does this work with ReShade?

**Comment by cichy45** [comment]
Have you tried the FPS limiter available inside CP2077 settings or setting one from Nvidia control panel?

**Comment by Qulox** [comment]
Forcing Fast VSync in Nvidia Control Panel seems to help a lot with input lag. Also, it does work with Reshade

**Comment by Onlineman19** [comment]
> Forcing Fast VSync in Nvidia Control Panel seems to help a lot with input lag. Also, it does work with Reshade

Thanks, good to know! Now I wonder if this would work with VR, like in the RealVR mod for CP2077.

**Comment by Onlineman19** [comment]
> Have you tried the FPS limiter available inside CP2077 settings or setting one from Nvidia control panel?
> 
> And yes, limiting FPS to lower number will make lag bigger, because that is the drawback of either DLSS Framegen, or FSR3 Framegen. Both are affected due to design.

After some testing,

RTSS introduces input lag the more FPS-limited it is. I have a 60Hz refresh rate monitor, so setting the limit at 60 introduces the most lag; at the 120 fps limit, the lag is barely noticeable.

The in-game limiter works at double the selected value. So, if you set the fps limit at 60 in settings, the actual in-game limit will be 120. Setting the fps limit to actually match my monitor refresh rate leads to constant microstutters.

The NVidia control panel is basically the same as the in-game limiter, only it actually limits the fps to the value you set.

Overall, it seems like limiting the game to the refresh rate of your monitor, which is something I always used to do, introduces serious issues with gameplay. For me, it seems like setting the limit in RTSS to double that of my monitor's refresh rate is the best bet, even though that puts my 3060ti at a constant 99% usage. In this case, VSync in the Nvidia control panel becomes unnecessary.

**Comment by Onlineman19** [comment]
Another question, theoretically, does this mod only work with games that support DLSS 3.0 + Frame Generation?

**Comment by cichy45** [comment]
> Another question, theoretically, does this mod only work with games that support DLSS 3.0 + Frame Generation?

From my understanding currently yes. It replaces DLSS Frame Generation with FSR3 frame generation. It requires RTX GPU. So the main target are RTX 2000 and 3000 GPUs, that do not have DLSS frame generation that nvidia locked to RTX 4000 only.

**Comment by Onlineman19** [comment]
> > Another question, theoretically, does this mod only work with games that support DLSS 3.0 + Frame Generation?
> 
> From my understanding currently yes. It replaces DLSS Frame Generation with FSR3 frame generation. It requires RTX GPU and game must support DLSS FG. So the main target are RTX 2000 and 3000 GPUs, that do not have DLSS frame generation that nvidia locked to RTX 4000 only.

I see, thanks for explaining.

**Comment by Onlineman19** [comment]
Yet another question, if someone were to mod DLSS3 + FG into a game that doesn't natively have it, would it work?

[https://www.youtube.com/watch?v=Qoibp4ocJc0](url)

**Comment by cichy45** [comment]
> Yet another question, if someone were to mod DLSS3 + FG into a game that doesn't natively have it, would it work?

Author of this mod might know, but I have no idea. Modding mod is like inception, we need to go deeper.

**Comment by Onlineman19** [comment]
> > Yet another question, if someone were to mod DLSS3 + FG into a game that doesn't natively have it, would it work?
> 
> Author of this mod might know, but I have no idea. Modding mod is like inception, we need to go deeper.

Lmao, true. Modding is amazing.

Also, just wanted to say thanks to those that work on making this mod, really great for a 3x series of RTX GPUs to get a bone.

FG comparison on a 3060ti:
![witcher3_QcN84QteUg](https://github.com/Nukem9/dlssg-to-fsr3/assets/79145410/d7dfe631-0c21-4e44-b1ae-cf4a026e4f40)
![witcher3_yZNq8aK6Lf](https://github.com/Nukem9/dlssg-to-fsr3/assets/79145410/0d9b1b39-cc27-45b6-b07b-3ee0d0566e8f)
