### ISSUE TITLE
G-sync seems to be working with FG. That's even better than native FSR3's FG since it doesn't support VRR

### ISSUE THREAD

**Issue by AeonMW2** [Nukem9/dlssg-to-fsr3#57]
so I just confirmed on my LG CX with VRR (realtime Hz) counter that g-sync is actually working normally with this mod.
that's wild, considering native FSR3's Frame Gen doesn't support VRR at all currently

**Comment by cichy45** [comment]
It does support it now. Only the very early demo from forspoken did not support it.

**Comment by AeonMW2** [comment]
> It does support it now. Only the very early demo from forspoken did not support it. Version from Avatar frontiers of pandora works with vrr and the released open source code also.

oh wow, thank you for the information. wasn't aware of that.
