### ISSUE TITLE
How to install on Starfield?

### ISSUE THREAD

**Issue by HelpMeModding** [Nukem9/dlssg-to-fsr3#77]

**Comment by RealmerFree** [comment]
I have no clue, when I enable frame gen the game just crashes.

**Comment by RealmerFree** [comment]
Just drop the files in your game folder, and then enable frame gen + dlss ingame

**Comment by HelpMeModding** [comment]
> Just drop the files in your game folder, and then enable frame gen + dlss ingame

Yeah, I figured it out, I was using an old 0.30 version, not 0.50

**Comment by RealmerFree** [comment]
I see. It is still unstable on Starfield sadly.
